# -*- coding: utf-8 -*-
"""Code automation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT7rSmj4mZbi-G4ZyKEXOic3Nl8qH6FC
"""

#!pip -q install python-docx pillow

import os, re, shutil
from pathlib import Path
from io import BytesIO

from docx import Document
from docx.text.paragraph import Paragraph
from docx.table import Table
from docx.oxml.text.paragraph import CT_P
from docx.oxml.table import CT_Tbl
from docx.oxml.ns import qn
from PIL import Image

#from google.colab import files


# ============================================================
# 1) Caption-type detection (REGEX, CASE-INSENSITIVE)
#    - Matches ALL map types at start of caption
#    - Enforces band ("on 2.4/5 GHz band") only for band-required types
# ============================================================

# Types that Ekahau captions often have WITHOUT "on 2.4/5 GHz band"
NO_BAND_TYPES = {
    "survey routes and access points",
    "associated access point",
    "bluetooth coverage",
}

# Band detector (tolerant of "2.4GHz" or "2.4 GHz", any case)
BAND_RE = re.compile(r"\bon\s+(?:the\s+)?(2\.4|5)\s*ghz\s+band\b", re.IGNORECASE)

# One regex that matches all your VIZ_TYPES at the START of the caption
# (case-insensitive, tolerant of hyphens/spaces in SNR)
TYPE_START_RE = re.compile(r"""
^(?P<type>
    #survey\s*routes\s*and\s*access\s*points|
    signal\s*strength|
    #secondary\s*signal\s*strength|
    #tertiary\s*signal\s*strength|
    (?:signal\s*(?:-|/)?\s*to\s*(?:-|/)?\s*noise\s*ratio)(?:\s*\(snr\))?|
    snr|
    noise|
    data\s*rate|
    throughput|
    channel\s*utilization|
    #channel\s*interference|
    #channel\s*width|
    spectrum\s*channel\s*power|
    #number\s*of\s*aps|
    #network\s*health|
    #network\s*issues|
    #interferers|
    #associated\s*access\s*point|
    #bluetooth\s*coverage
)\b
""", re.IGNORECASE | re.VERBOSE)


def norm_text(t: str) -> str:
    t = (t or "").replace("\u00A0", " ").replace("\n", " ").strip()
    t = re.sub(r"\s+", " ", t)
    if t.endswith("."):
        t = t[:-1]
    return t


def canonical_type(type_text: str) -> str:
    """Normalize the matched type into a stable lowercase key."""
    s = (type_text or "").lower()
    s = s.replace("–", "-").replace("—", "-")
    s = re.sub(r"\s+", " ", s).strip()

    # Collapse SNR variants into a single key
    if s == "snr" or ("noise ratio" in s and "signal" in s):
        return "snr"

    return s


def is_caption_text(s: str) -> bool:
    """
    Generic caption matcher:
    - Allows optional 'Figure 12:' prefix
    - Requires a supported type at the start (TYPE_START_RE)
    - Requires the word 'for' somewhere (reduces false matches on headings)
    - Enforces band only when type is NOT in NO_BAND_TYPES
    """
    s = norm_text(s)
    if not s:
        return False

    # remove "Figure 12:" / "Fig 12 - " prefix
    s2 = re.sub(r"^(figure|fig)\s*\d+\s*[:\-]\s*", "", s, flags=re.IGNORECASE).strip()

    m = TYPE_START_RE.match(s2)
    if not m:
        return False

    # Typical Ekahau captions include "for <location ...>"
    if re.search(r"\bfor\b", s2, re.IGNORECASE) is None:
        return False

    t_key = canonical_type(m.group("type"))

    # If this caption type normally has a band, enforce it
    if t_key not in NO_BAND_TYPES:
        if BAND_RE.search(s2) is None:
            return False

    return True


# ============================================================
# 2) Naming helpers
# ============================================================
def device_from_docx(docx_path: str) -> str:
    stem = Path(docx_path).stem
    parts = stem.strip().split()
    return parts[0] if parts else stem


def safe_filename(text: str, max_len: int = 170) -> str:
    s = norm_text(text)
    s = re.sub(r"[\\/:*?\"<>|]+", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    s = s[:max_len].rstrip() if len(s) > max_len else s
    return s


def unique_path(path: str) -> str:
    if not os.path.exists(path):
        return path
    root, ext = os.path.splitext(path)
    k = 2
    while True:
        p2 = f"{root}_{k}{ext}"
        if not os.path.exists(p2):
            return p2
        k += 1


# ============================================================
# 3) Iterate BODY paragraphs only (includes tables/cells)
# ============================================================
def iter_block_items(parent):
    parent_elm = parent.element.body if hasattr(parent, "element") and hasattr(parent.element, "body") else parent._tc
    for child in parent_elm.iterchildren():
        if isinstance(child, CT_P):
            yield Paragraph(child, parent)
        elif isinstance(child, CT_Tbl):
            yield Table(child, parent)


def iter_all_paragraphs(doc: Document):
    def walk(parent):
        for item in iter_block_items(parent):
            if isinstance(item, Paragraph):
                yield item
            elif isinstance(item, Table):
                for row in item.rows:
                    for cell in row.cells:
                        yield from walk(cell)
    yield from walk(doc)


# ============================================================
# 4) Extract image relationship IDs (DrawingML + VML)
# ============================================================
REL_NS    = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
OFFICE_NS = "urn:schemas-microsoft-com:office:office"

def paragraph_image_rids(p: Paragraph):
    el = p._p

    # DrawingML
    for blip in el.xpath(".//a:blip"):
        rid = blip.get(qn("r:embed"))
        if rid:
            yield rid

    # VML
    for imdata in el.xpath(".//*[local-name()='imagedata']"):
        rid = imdata.get(f"{{{REL_NS}}}id") or imdata.get(f"{{{OFFICE_NS}}}relid")
        if rid:
            yield rid


# ============================================================
# 5) Image heuristics: main vs scale
# ============================================================
def ext_from_part(part) -> str:
    ext = Path(str(part.partname)).suffix.lower().lstrip(".")
    return ext if ext else "png"

def get_dims(blob: bytes):
    try:
        im = Image.open(BytesIO(blob))
        return im.size[0], im.size[1]
    except Exception:
        return 0, 0

def looks_like_scale(w: int, h: int) -> bool:
    if w <= 0 or h <= 0:
        return False
    aspect = w / float(h)
    return (aspect >= 2.0 and h <= 260 and w >= 150)

def score(blob: bytes) -> int:
    w, h = get_dims(blob)
    return (w * h) if (w and h) else len(blob)


# ============================================================
# 6) Extract maps for each caption (caption can be above OR below)
#    - saves 1 image too (scale naming if scale-like)
# ============================================================
def extract_maps_best_side_save_one(docx_path: str, out_dir: str, MIN_ICON_AREA: int = 250):
    os.makedirs(out_dir, exist_ok=True)

    device = device_from_docx(docx_path)
    doc = Document(docx_path)

    blocks = []
    for p in iter_all_paragraphs(doc):
        t = norm_text(p.text)
        blocks.append({
            "text": t,
            "is_caption": is_caption_text(t),
            "rids": list(paragraph_image_rids(p))
        })

    cap_idxs = [i for i, b in enumerate(blocks) if b["is_caption"]]

    def resolve_imgs(rids):
        rids = list(dict.fromkeys(rids))
        imgs = []
        for rid in rids:
            part = doc.part.related_parts.get(rid)
            if part is None:
                continue
            blob = part.blob
            w, h = get_dims(blob)
            area = (w * h) if (w and h) else 0

            if area and area < MIN_ICON_AREA:
                continue

            imgs.append({
                "blob": blob,
                "ext": ext_from_part(part),
                "w": w, "h": h,
                "is_scale": looks_like_scale(w, h),
                "score": score(blob),
            })
        return imgs

    def pick_main_scale(imgs):
        imgs_sorted = sorted(imgs, key=lambda x: x["score"], reverse=True)
        main = imgs_sorted[0]
        rest = imgs_sorted[1:]
        scale_candidates = [x for x in rest if x["is_scale"]]
        if scale_candidates:
            scale = sorted(scale_candidates, key=lambda x: x["score"])[0]
        else:
            scale = sorted(rest, key=lambda x: x["score"])[0]
        return main, scale

    def side_quality(imgs):
        n = len(imgs)
        if n == 0:
            return -10**9
        has_scale_like = any(x["is_scale"] for x in imgs)
        q = 0
        q += 200 if n == 2 else 0
        q -= 30 * abs(n - 2)
        q += 40 if has_scale_like else 0
        return q

    saved = []
    skipped0 = 0

    for pos, i in enumerate(cap_idxs):
        caption = blocks[i]["text"]
        cap_safe = safe_filename(caption)

        prev_i = cap_idxs[pos - 1] if pos > 0 else None
        next_i = cap_idxs[pos + 1] if (pos + 1 < len(cap_idxs)) else len(blocks)

        # AFTER caption region
        rids_after = []
        for b in blocks[i+1:next_i]:
            rids_after.extend(b["rids"])
        imgs_after = resolve_imgs(rids_after)

        # BEFORE caption region
        rids_before = []
        start = (prev_i + 1) if prev_i is not None else 0
        for b in blocks[start:i]:
            rids_before.extend(b["rids"])
        imgs_before = resolve_imgs(rids_before)

        imgs = imgs_after if side_quality(imgs_after) >= side_quality(imgs_before) else imgs_before

        if len(imgs) == 0:
            skipped0 += 1
            continue

        # save single image
        if len(imgs) == 1:
            one = imgs[0]
            suffix = "_scale" if one["is_scale"] else ""
            outp = unique_path(os.path.join(out_dir, f"{device}_{cap_safe}{suffix}.{one['ext']}"))
            with open(outp, "wb") as f:
                f.write(one["blob"])
            saved.append(outp)
            continue

        # save main+scale
        main, scale = pick_main_scale(imgs)
        main_path  = unique_path(os.path.join(out_dir, f"{device}_{cap_safe}.{main['ext']}"))
        scale_path = unique_path(os.path.join(out_dir, f"{device}_{cap_safe}_scale.{scale['ext']}"))

        with open(main_path, "wb") as f:
            f.write(main["blob"])
        with open(scale_path, "wb") as f:
            f.write(scale["blob"])

        saved.extend([main_path, scale_path])

    return {
        "saved_paths": saved,
        "matched_captions": len(cap_idxs),
        "skipped_zero_image": skipped0,
        "device": device,
    }


# ============================================================
# 7) Batch runner: many DOCX -> folders under /content/out
# ============================================================
def process_many_docx_local(docx_paths, out_root="out",
                            download_per_docx_zip=False,
                            also_make_master_zip=True):
    os.makedirs(out_root, exist_ok=True)

    # define zip_dir ONCE (so it exists even if loop changes)
    zip_dir = os.path.join(out_root, "_zips")
    os.makedirs(zip_dir, exist_ok=True)

    zip_files = []

    for docx_path in docx_paths:
        if not os.path.exists(docx_path):
            print(f"SKIP (not found): {docx_path}")
            continue

        stem = Path(docx_path).stem
        device = device_from_docx(docx_path)

        out_dir = os.path.join(out_root, f"{device}_{stem}")
        if os.path.exists(out_dir):
            shutil.rmtree(out_dir)
        os.makedirs(out_dir, exist_ok=True)

        print("\n====================================")
        print("DOCX:", docx_path)
        print("OUT :", out_dir)

        res = extract_maps_best_side_save_one(docx_path, out_dir, MIN_ICON_AREA=250)

        print("Matched captions:", res["matched_captions"])
        print("Saved files    :", len(res["saved_paths"]))
        print("Zero-image caps:", res["skipped_zero_image"])

        # Per-DOCX ZIP (this is the one you already see in terminal)
        zip_base = os.path.join(zip_dir, f"{device}_{stem}_extracted")
        zip_file = shutil.make_archive(zip_base, "zip", out_dir)
        print("ZIP created:", zip_file)
        zip_files.append(zip_file)

    # MASTER ZIP — only if checkbox is on
    if also_make_master_zip and zip_files:
        print("Creating MASTER ZIP (can be slow for large outputs)...")
        master_base = os.path.join(zip_dir, "ALL_EXTRACTED")
        master_zip = shutil.make_archive(master_base, "zip", out_root)
        print("MASTER ZIP created:", master_zip)
        zip_files.append(master_zip)

    return zip_files




if __name__ == "__main__":
    # === RUN ONLY DOCX EXTRACTION ===
    # Change this to wherever Streamlit stores uploaded files
    DOCX_DIR = "uploads"      # or "." or "/tmp/..." depending on your app.py
    OUT_DIR  = "out"          # where extracted images will go

    docx_paths = sorted([str(p) for p in Path(DOCX_DIR).glob("*.docx")])

    if not docx_paths:
        raise ValueError(f"No DOCX files found in: {DOCX_DIR}")

    # Fast settings:
    # - also_make_master_zip=False  (skip slow master zip)
    # - per-doc zip still ok
    process_many_docx_local(
        docx_paths,
        out_root=OUT_DIR,
        download_per_docx_zip=False,
        also_make_master_zip=False
    )

    print("\nDONE: Extraction only.")
    print("Output folder:", OUT_DIR)