# -*- coding: utf-8 -*-
"""rvr_final_generalized_for_project_optimized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a7_Hy3EjBARDqiaR8poLfR-4XnU1ChIV

# RvR — Parameter vs Range (ft) — Generalized (Anchored multi-floor)

This notebook produces **Range vs Parameter** curves from Ekahau exports for **multiple routers, floors, and bands**.

## Quick start (Colab)
1. Run **Setup** + **Config**.
2. Upload into `/content/inputs`:
   - **1 master floorplan** `.esx` (contains floorPlans & images)
   - **N router survey** `.esx` files (one per router)
   - Ekahau-exported `*band_output.csv` files for the chosen parameter
   - *(optional but recommended)* `site_geometry.json` (anchors + cached DUTs)
3. Run remaining cells **top → bottom** (or Runtime → Run all).

## What you get
- Distance normalization across floors using **2 anchors per floor** (stair + ref) chained back to the **base floor**
- **DUT location per router** (auto-extracted from router ESX if possible)
- Curves aggregated in distance bins (default **2 ft**)
- Comparison plots:
  - Routers-by-floor (percent & actual)
  - Floors-by-router (percent & actual)
- One ZIP containing **all outputs** (tables + plots + metadata)

> Tip: If you re-run often, keep `site_geometry.json` in `/content/inputs` to skip anchor clicking.
"""

# =========================
# 1) Install dependencies (Colab)
# =========================

"""## Config"""

# =========================
# 2) Imports + Global Config (All-parameter ready)
# =========================
import os, re, json, zipfile, glob, hashlib
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from PIL import Image

try:
    from IPython.display import display, HTML
except Exception:
    def display(x=None):
        if x is None:
            return
        try:
            import pandas as _pd  # type: ignore
            if isinstance(x, _pd.DataFrame):
                print(x.head(20).to_string(index=False))
            else:
                print(x)
        except Exception:
            print(x)
    class HTML(str):
        pass
try:
    from google.colab import files
    IN_COLAB = True
except Exception:
    IN_COLAB = False

# ----------------------
# Local (VS Code) interactive point picker
# ----------------------
def pick_points_local(image_path: str, n_points: int = 1, title: str = "Click points"):
    """Pick N points in a local desktop session (VS Code) using OpenCV.

    - Left-click to add a point.
    - The window closes automatically after N clicks.
    - Press ESC to cancel (raises KeyboardInterrupt).
    """
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(image_path)

    pts = []
    disp = img.copy()
    win = f"{title} :: {os.path.basename(image_path)}"
    cv2.namedWindow(win, cv2.WINDOW_NORMAL)

    def _cb(event, x, y, flags, param):
        nonlocal disp
        if event == cv2.EVENT_LBUTTONDOWN:
            pts.append((float(x), float(y)))
            cv2.circle(disp, (x, y), 6, (0, 0, 255), -1)
            cv2.putText(disp, str(len(pts)-1), (x+10, y-10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,0,255), 2)
            cv2.imshow(win, disp)

    cv2.setMouseCallback(win, _cb)
    cv2.imshow(win, disp)

    while True:
        key = cv2.waitKey(20) & 0xFF
        if key == 27:  # ESC
            cv2.destroyWindow(win)
            raise KeyboardInterrupt("Point picking cancelled (ESC).")

        if len(pts) >= int(n_points):
            cv2.destroyWindow(win)
            break

    return np.array(pts, dtype=float)

def pick_points(image_path: str, n_points: int = 1, title: str = "Click points"):
    """Pick points in Colab (JS) or locally (OpenCV), depending on environment."""
    if IN_COLAB:
        return pick_points_colab(image_path, n_points=n_points, title=title)
    return pick_points_local(image_path, n_points=n_points, title=title)

FEET_PER_METER = 3.280839895

# -------------------------------------------------
# ---- PARAMETER PRESETS (choose by display name)
# -------------------------------------------------
PARAM_PRESETS = {
    "Signal Strength": {
        "PARAM_KEY": "signal_strength",
        "PARAM_PRETTY": "Signal Strength",
        "PARAM_UNIT": "dBm",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Secondary Signal Strength": {
        "PARAM_KEY": "secondary_signal_strength",
        "PARAM_PRETTY": "Secondary Signal Strength",
        "PARAM_UNIT": "dBm",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Tertiary Signal Strength": {
        "PARAM_KEY": "tertiary_signal_strength",
        "PARAM_PRETTY": "Tertiary Signal Strength",
        "PARAM_UNIT": "dBm",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "SNR": {
        "PARAM_KEY": "snr",
        "PARAM_PRETTY": "SNR",
        "PARAM_UNIT": "dB",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "max",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Channel Interference": {
        "PARAM_KEY": "channel_interference",
        "PARAM_PRETTY": "Channel Interference",
        "PARAM_UNIT": "dB",
        "HIGHER_IS_BETTER": False,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Number of Access Points": {
        "PARAM_KEY": "number_of_access_points",
        "PARAM_PRETTY": "Number of Access Points",
        "PARAM_UNIT": "count",
        "HIGHER_IS_BETTER": False,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Noise": {
        "PARAM_KEY": "noise",
        "PARAM_PRETTY": "Noise",
        "PARAM_UNIT": "dBm",
        "HIGHER_IS_BETTER": False,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Data Rate": {
        "PARAM_KEY": "data_rate",
        "PARAM_PRETTY": "Data Rate",
        "PARAM_UNIT": "Mbps",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "max",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Throughput": {
        "PARAM_KEY": "throughput",
        "PARAM_PRETTY": "Throughput",
        "PARAM_UNIT": "Mbps",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "max",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Associated Access Points": {
        "PARAM_KEY": "associated_access_points",
        "PARAM_PRETTY": "Associated Access Points",
        "PARAM_UNIT": "count",
        "HIGHER_IS_BETTER": False,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Channel Utilization": {
        "PARAM_KEY": "channel_utilization",
        "PARAM_PRETTY": "Channel Utilization",
        "PARAM_UNIT": "%",
        "HIGHER_IS_BETTER": False,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Spectrum Channel Power": {
        "PARAM_KEY": "spectrum_channel_power",
        "PARAM_PRETTY": "Spectrum Channel Power",
        "PARAM_UNIT": "dBm",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Network Health": {
        "PARAM_KEY": "network_health",
        "PARAM_PRETTY": "Network Health",
        "PARAM_UNIT": "score",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "max",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Network Issues": {
        "PARAM_KEY": "network_issues",
        "PARAM_PRETTY": "Network Issues",
        "PARAM_UNIT": "count",
        "HIGHER_IS_BETTER": False,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Bluetooth Coverage": {
        "PARAM_KEY": "bluetooth_coverage",
        "PARAM_PRETTY": "Bluetooth Coverage",
        "PARAM_UNIT": "%",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "max",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Access Points": {
        "PARAM_KEY": "access_points",
        "PARAM_PRETTY": "Access Points",
        "PARAM_UNIT": "count",
        "HIGHER_IS_BETTER": False,
        "PERCENT_MODE": "minmax",
        "BANDS": ["2.4GHz", "5GHz"],
    },
    "Channel Width": {
        "PARAM_KEY": "channel_width",
        "PARAM_PRETTY": "Channel Width",
        "PARAM_UNIT": "MHz",
        "HIGHER_IS_BETTER": True,
        "PERCENT_MODE": "max",
        "BANDS": ["2.4GHz", "5GHz"],
    },
}

# -------------------------------------------------
# ---- USER SETTINGS (pick one preset name)
# -------------------------------------------------
PARAM_NAME = 'Data Rate'

# Optional overrides (leave None to use preset defaults)
BANDS_OVERRIDE = None              # e.g. ["5GHz"] or ["2.4GHz","5GHz"]
PERCENT_MODE_OVERRIDE = None       # "minmax" or "max"
OUT_BASE_OVERRIDE = None           # e.g. "/content/rvr_custom_run"

# Apply preset
_PRESET = PARAM_PRESETS[PARAM_NAME]
PARAM_KEY        = _PRESET["PARAM_KEY"]
PARAM_PRETTY     = _PRESET["PARAM_PRETTY"]
PARAM_UNIT       = _PRESET["PARAM_UNIT"]
HIGHER_IS_BETTER = _PRESET["HIGHER_IS_BETTER"]
PERCENT_MODE     = _PRESET["PERCENT_MODE"]
BANDS            = _PRESET["BANDS"]

# Apply overrides if provided
if BANDS_OVERRIDE is not None:
    BANDS = list(BANDS_OVERRIDE)
if PERCENT_MODE_OVERRIDE is not None:
    PERCENT_MODE = str(PERCENT_MODE_OVERRIDE)

# Distance binning for curve (feet)
BIN_FT = 2.0

# Statistic for curve line: "p50" (median) or "mean"
Y_STAT = "p50"

# Draw spread band (p10..p90) for overlap debugging
FILL_SPREAD = False

# 3D distance option (needs floor_elevation_m in site_geometry.json)
USE_3D = False

# Input/output folders (Colab)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_DIR = 'runs/router/rvr_inputs/data_rate'
OUT_BASE = 'runs/router/rvr_outputs/data_rate'

os.makedirs(INPUT_DIR, exist_ok=True)
os.makedirs(OUT_BASE, exist_ok=True)

print("[INFO] PARAM_NAME:", PARAM_NAME)
print("[INFO] PARAM:", PARAM_PRETTY, "| key:", PARAM_KEY, "| unit:", PARAM_UNIT)
print("[INFO] HIGHER_IS_BETTER:", HIGHER_IS_BETTER, "| PERCENT_MODE:", PERCENT_MODE, "| bands:", BANDS)
print("[INFO] OUT_BASE:", OUT_BASE)
# ----------------------
# Performance (caching)
# ----------------------
# Caches parsed ESX JSON, extracted floorplan images, and per-CSV aggregated curves.
# Safe to disable if you want to force a full recompute.
CACHE_ENABLED = True
CACHE_VERBOSE = False
CACHE_VERSION = "v1"  # bump to invalidate older cache files

CACHE_DIR = os.path.join(OUT_BASE, "_cache")
os.makedirs(CACHE_DIR, exist_ok=True)

print("[INFO] CACHE_ENABLED:", CACHE_ENABLED, "| CACHE_DIR:", CACHE_DIR)

"""## Inputs (upload / manage)"""

# =========================
# 3) Input Manager (Local / VS Code)
# =========================
def list_dir(path):
    if not os.path.isdir(path):
        os.makedirs(path, exist_ok=True)
        return []
    return sorted([os.path.join(path, f) for f in os.listdir(path)])

def delete_dir_contents(path):
    if not os.path.isdir(path):
        return
    for fn in os.listdir(path):
        fp = os.path.join(path, fn)
        try:
            if os.path.isdir(fp):
                import shutil
                shutil.rmtree(fp)
            else:
                os.remove(fp)
        except Exception as e:
            print(f"[WARN] Could not delete: {fp} | {e}")

# --- Local usage ---
# Put your files into INPUT_DIR (shown below), then run this script.
# Expected in INPUT_DIR:
#   - 1 master floorplan .esx (contains floorPlans & images)
#   - N router survey .esx files (one per router)
#   - Ekahau-exported *band_output.csv files for the chosen PARAM_NAME
#   - Optional: site_geometry.json (anchors + cached DUTs)
#
# Tip: You can override INPUT_DIR via environment variable RVR_INPUT_DIR.

DELETE_EXISTING_INPUTS = False  # set True ONLY if you want to wipe INPUT_DIR before running

if DELETE_EXISTING_INPUTS:
    print("[INFO] Deleting existing inputs...")
    delete_dir_contents(INPUT_DIR)

existing_files = list_dir(INPUT_DIR)

print("---")
if not existing_files:
    print("[WARN] INPUT_DIR is empty. Copy your .esx and *_band_output.csv files into this folder, then re-run.")
else:
    print(f"[INFO] Found {len(existing_files)} item(s) in INPUT_DIR:")
    for p in existing_files:
        print(" -", os.path.basename(p))


"""## Core helpers (ESX parsing + point picker)"""

# =========================
# 4) Helpers (ESX parsing + Colab click picker)
# =========================
def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

# ----------------------
# ESX caching (in-memory + on-disk)
# ----------------------
_FILE_HASH_CACHE = {}
_ESX_JSON_MEM = {}

def _file_sha_cached(path: str) -> str:
    """Compute sha256 once per (path,size,mtime)."""
    st = os.stat(path)
    key = (path, st.st_size, int(st.st_mtime))
    if key in _FILE_HASH_CACHE:
        return _FILE_HASH_CACHE[key]
    sha = sha256_file(path)
    # purge older keys for same path
    for k in list(_FILE_HASH_CACHE.keys()):
        if k[0] == path and k != key:
            _FILE_HASH_CACHE.pop(k, None)
    _FILE_HASH_CACHE[key] = sha
    return sha

def _safe_member_name(member: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", member)

def read_esx_json(esx_path: str, member: str) -> dict:
    """Read JSON member from an .esx (zip). Uses CACHE_DIR if enabled."""
    if not globals().get("CACHE_ENABLED", False):
        with zipfile.ZipFile(esx_path, "r") as zf:
            return json.loads(zf.read(member).decode("utf-8"))

    esx_sha = _file_sha_cached(esx_path)
    mem_key = (esx_sha, member)
    if mem_key in _ESX_JSON_MEM:
        return _ESX_JSON_MEM[mem_key]

    cache_path = os.path.join(CACHE_DIR, f"{CACHE_VERSION}__esxjson__{esx_sha}__{_safe_member_name(member)}.json")
    if os.path.exists(cache_path):
        with open(cache_path, "r", encoding="utf-8") as f:
            obj = json.load(f)
        _ESX_JSON_MEM[mem_key] = obj
        if globals().get("CACHE_VERBOSE", False):
            print(f"[CACHE] hit esx json: {os.path.basename(esx_path)} :: {member}")
        return obj

    with zipfile.ZipFile(esx_path, "r") as zf:
        obj = json.loads(zf.read(member).decode("utf-8"))

    _ESX_JSON_MEM[mem_key] = obj
    try:
        with open(cache_path, "w", encoding="utf-8") as f:
            json.dump(obj, f)
    except Exception as e:
        if globals().get("CACHE_VERBOSE", False):
            print("[CACHE] write failed:", cache_path, e)
    return obj

def extract_floor_images(master_esx: str, out_dir: str) -> dict:
    """
    Extract floor plan images from master ESX using image-{imageId}.
    Returns FLOORS_META: {floorName: {floorPlanId, metersPerUnit, img_path, w,h}}
    Uses CACHE_DIR if enabled.
    """
    os.makedirs(out_dir, exist_ok=True)

    esx_sha = _file_sha_cached(master_esx) if globals().get("CACHE_ENABLED", False) else None
    meta_cache = os.path.join(CACHE_DIR, f"{CACHE_VERSION}__floorsmeta__{esx_sha}.json") if esx_sha else None

    if globals().get("CACHE_ENABLED", False) and meta_cache and os.path.exists(meta_cache):
        try:
            with open(meta_cache, "r", encoding="utf-8") as f:
                cached = json.load(f)
            # Validate image paths exist; if yes, return immediately
            ok = True
            for _, info in cached.items():
                if not os.path.exists(info.get("img_path", "")):
                    ok = False
                    break
            if ok:
                if globals().get("CACHE_VERBOSE", False):
                    print("[CACHE] hit floors meta:", os.path.basename(master_esx))
                return cached
        except Exception:
            pass  # fall through to re-extract

    fps = read_esx_json(master_esx, "floorPlans.json")["floorPlans"]

    floors_meta = {}
    with zipfile.ZipFile(master_esx, "r") as zf:
        names = set(zf.namelist())
        for fp in fps:
            name = str(fp.get("name", "")).strip()
            image_id = fp.get("imageId")
            member = f"image-{image_id}"
            if member not in names:
                continue

            safe = re.sub(r"[^A-Za-z0-9_-]+", "_", name)
            out_path = os.path.join(out_dir, f"{safe}.png")

            if os.path.exists(out_path):
                img = cv2.imread(out_path)
            else:
                img = cv2.imdecode(np.frombuffer(zf.read(member), np.uint8), cv2.IMREAD_COLOR)
                cv2.imwrite(out_path, img)

            h, w = img.shape[:2]
            floors_meta[name] = {
                "floorPlanId": fp.get("id"),
                "metersPerUnit": fp.get("metersPerUnit", 1.0),
                "img_path": out_path,
                "w": int(w),
                "h": int(h),
            }

    if globals().get("CACHE_ENABLED", False) and meta_cache:
        try:
            with open(meta_cache, "w", encoding="utf-8") as f:
                json.dump(floors_meta, f)
        except Exception as e:
            if globals().get("CACHE_VERBOSE", False):
                print("[CACHE] floors meta write failed:", meta_cache, e)

    return floors_meta

def pick_points_colab(image_path, n_points=1, title="Click points"):
    if not IN_COLAB:
        raise RuntimeError("pick_points_colab only works in Google Colab.")

    from base64 import b64encode
    from google.colab.output import eval_js

    img = Image.open(image_path).convert("RGB")
    W, H = img.size
    with open(image_path, "rb") as f:
        data = b64encode(f.read()).decode("utf-8")

    display(HTML(
        "<div style='font-family:sans-serif; margin:8px 0;'>"
        f"<h3 style='margin:0 0 6px 0;'>{title}</h3>"
        f"<p style='margin:0 0 10px 0;'>Click {n_points} point(s). After last click, it returns automatically.</p>"
        "</div>"
    ))

    js = f'''
    async function pickPoints() {{
      const n = {n_points};
      const imgW = {W}, imgH = {H};

      const container = document.createElement('div');
      container.style.position = 'relative';
      container.style.display = 'inline-block';
      container.style.border = '1px solid #ddd';
      container.style.marginBottom = '12px';

      const img = document.createElement('img');
      img.src = "data:image/png;base64,{data}";
      img.style.maxWidth = "95vw";
      img.style.height = "auto";
      img.style.display = "block";
      container.appendChild(img);

      const canvas = document.createElement('canvas');
      canvas.style.position = 'absolute';
      canvas.style.left = 0;
      canvas.style.top = 0;
      canvas.style.pointerEvents = 'none';
      container.appendChild(canvas);

      document.body.appendChild(container);

      await new Promise(r => setTimeout(r, 50));
      const rect = img.getBoundingClientRect();
      canvas.width = rect.width;
      canvas.height = rect.height;

      const ctx = canvas.getContext('2d');
      ctx.font = '14px sans-serif';

      const pts = [];
      function drawPoint(x, y, idx) {{
        ctx.beginPath();
        ctx.arc(x, y, 5, 0, 2*Math.PI);
        ctx.fill();
        ctx.fillText(String(idx), x+8, y-8);
      }}

      return await new Promise(resolve => {{
        img.addEventListener('click', (e) => {{
          const r = img.getBoundingClientRect();
          const x_disp = (e.clientX - r.left);
          const y_disp = (e.clientY - r.top);

          const x_px = x_disp * (imgW / r.width);
          const y_px = y_disp * (imgH / r.height);

          pts.push([x_px, y_px]);
          drawPoint(x_disp, y_disp, pts.length - 1);

          if (pts.length >= n) {{
            container.remove();
            resolve(pts);
          }}
        }});
      }});
    }}
    pickPoints();
    '''
    pts = eval_js(js)
    return np.array(pts, dtype=float)

def infer_router_key_from_path(path: str) -> str:
    b = os.path.basename(path)
    # common pattern: "TMO-G5AR February 2026 Survey (No APs).esx"
    m = re.match(r"^([A-Za-z0-9_-]+)\s+", b)
    if m:
        return m.group(1)
    return os.path.splitext(b)[0]

def router_display_name(esx_path: str) -> str:
    # Cleans up router name from the ESX path for display
    b = os.path.basename(esx_path)
    # Example: "TMO-G5AR February 2026 Survey (No APs).esx" -> "TMO-G5AR"
    s = str(b)
    s = re.sub(r"\s*February\s*\d{4}\s*Survey\s*\(No APs\)\.esx$", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\s*Survey\s*\(No APs\)\.esx$", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\.esx$", "", s, flags=re.IGNORECASE) # Remove .esx if still present
    s = s.strip(" -_")
    return s if s else b # Fallback to base filename if cleanup results in empty string


print("[OK] Helpers loaded.")

"""## Discover inputs (master ESX, router ESX, parameter CSVs)"""

# =========================
# 5) Discover inputs (master ESX, router ESX, parameter CSVs)
# =========================
all_esx = sorted(glob.glob(os.path.join(INPUT_DIR, "*.esx")))
if not all_esx:
    raise FileNotFoundError("No .esx found in INPUT_DIR. Upload floorplan ESX + router ESX files.")

# Heuristic: master floorplan ESX is the one with 'floor' in name
MASTER_ESX = None
for p in all_esx:
    if "floor" in os.path.basename(p).lower():
        MASTER_ESX = p
        break
if MASTER_ESX is None:
    MASTER_ESX = all_esx[0]

router_esx_paths = [p for p in all_esx if os.path.abspath(p) != os.path.abspath(MASTER_ESX)]

print("[INFO] MASTER_ESX:", os.path.basename(MASTER_ESX))
print("[INFO] Router ESX files:", len(router_esx_paths))
for p in router_esx_paths:
    print(" -", os.path.basename(p))

# Scan CSV outputs and filter by this PARAM_KEY
csvs = sorted(glob.glob(os.path.join(INPUT_DIR, "*band_output.csv")))
print("[INFO] Found CSV outputs:", len(csvs))

CSV_RE = re.compile(
    r"^(?P<router>.+?)_(?P<param>.+?)\s+for\s+(?P<floor>.+?)\s+on\s+(?P<band>2\.4|5)\s*GHz\s+band_output\.csv$",
    re.I
)

def canonical_param_from_text(text: str):
    t = re.sub(r"\s+", " ", str(text).strip()).lower()
    if "signal strength" in t or t == "rssi":
        return "signal_strength"
    if "snr" in t or "signal to noise" in t:
        return "snr"
    if "channel interference" in t or "channel interferecne" in t:
        return "channel_interference"
    if "data rate" in t or "datarate" in t:
        return "data_rate"
    if "throughput" in t:
        return "throughput"
    if "channel utilization" in t:
        return "channel_utilization"
    if "spectrum channel power" in t:
        return "spectrum_channel_power"
    return None

meta_rows = []
for p in csvs:
    m = CSV_RE.match(os.path.basename(p))
    if not m:
        continue
    router_key = m.group("router").strip()
    pkey = canonical_param_from_text(m.group("param"))
    if pkey != PARAM_KEY:
        continue
    floor_name = m.group("floor").strip()
    band = f"{m.group('band')}GHz"
    meta_rows.append({
        "router_key": router_key,
        "floor_name": floor_name,
        "band": band,
        "csv_path": p
    })

META = pd.DataFrame(meta_rows)
if META.empty:
    raise FileNotFoundError(f"No CSVs matched PARAM_KEY={PARAM_KEY}. Check filenames in INPUT_DIR.")

print("[INFO] Matched CSVs for this parameter:", len(META))
display(META.head(20))

"""## Extract floor plans from master ESX"""

# =========================
# 6) Load floors from master ESX + extract floor images
# =========================
FLOOR_IMG_DIR = os.path.join(OUT_BASE, "_floor_images")
FLOORS_META = extract_floor_images(MASTER_ESX, FLOOR_IMG_DIR)
if not FLOORS_META:
    raise RuntimeError("No floor images extracted from MASTER_ESX. Is this a valid floorplan ESX?")

print("[INFO] Floors available in MASTER_ESX:")
for k,v in FLOORS_META.items():
    print(f" - {k:20s} | {v['w']}x{v['h']} px | mpu={v['metersPerUnit']} | {os.path.basename(v['img_path'])}")

# Floors to use: intersection between floors in master and floors in CSVs
floors_in_csv = sorted(set(META["floor_name"].tolist()))
FLOORS_TO_USE = [f for f in floors_in_csv if f in FLOORS_META]
if not FLOORS_TO_USE:
    FLOORS_TO_USE = list(FLOORS_META.keys())

print("[INFO] FLOORS_TO_USE:", FLOORS_TO_USE)

"""## Router list (display names)"""

# =========================
# 7) Load router display names from router ESX
# =========================
ROUTERS = {}
for p in router_esx_paths:
    key = infer_router_key_from_path(p)
    ROUTERS[key] = {"path": p, "display": router_display_name(p)}

print("[INFO] Routers discovered:", len(ROUTERS))
for k,v in ROUTERS.items():
    print(f" - {k:10s} | {v['display']}")

"""## Geometry alignment + DUT extraction

### auto dut extraction
"""

# =========================
# 8) Anchors & DUT (site_geometry.json)  [PAIRWISE / CHAIN ALIGNMENT]
#   - If /content/inputs/site_geometry.json exists: load it, no clicking
#   - Else: create new site_geometry.json via clicking (Colab)  [ANCHORS UNCHANGED]
#   - DUT: auto-extract PER ROUTER from router ESX JSON (accessPoints mine:true + positions)
#       * If multiple mine:true candidates -> choose one minimizing distance to other routers' DUTs
# =========================
import os, re, json, zipfile
import numpy as np

SITE_GEOM_INPUT = os.path.join(INPUT_DIR, "site_geometry.json")  # /content/inputs/site_geometry.json
SITE_GEOM_FALLBACK = os.path.join(OUT_BASE, "site_geometry.json")
SITE_GEOM_PATH = SITE_GEOM_INPUT if os.path.exists(SITE_GEOM_INPUT) else SITE_GEOM_FALLBACK

FORCE_RECLICK = False  # ✅ set True only when you want to re-pick anchors (NOT DUT)
ALLOW_DUT_CLICK_FALLBACK = True  # if DUT cannot be extracted from ESX, allow clicking as fallback

BASE_FLOOR = "Kitchen" if "Kitchen" in FLOORS_META else FLOORS_TO_USE[0]
print("[INFO] BASE_FLOOR:", BASE_FLOOR)
print("[INFO] SITE_GEOM_PATH:", SITE_GEOM_PATH)

# Optional chaining:
# ALIGN_TO_MAP = {"Upper Room": "Living Room"}
ALIGN_TO_MAP = {}

def _check_reachable_to_base(site: dict, floors: list, base_floor: str):
    links = site.get("links", {})
    for f in floors:
        if f == base_floor:
            continue
        seen = set()
        cur = f
        while cur != base_floor:
            if cur in seen:
                raise ValueError(f"Cycle detected in links while resolving {f}.")
            seen.add(cur)
            if cur not in links:
                raise ValueError(f"Missing link for floor '{cur}'.")
            cur = links[cur].get("align_to")
            if not cur:
                raise ValueError(f"Link for '{seen}' missing 'align_to'.")
            if cur not in floors:
                raise ValueError(f"Link for '{seen}' points to unknown floor '{cur}'.")
    return True

def load_or_create_site_geometry():
    # ----------------------------
    # 1) Load existing if present in inputs (preferred)
    # ----------------------------
    if (not FORCE_RECLICK) and os.path.exists(SITE_GEOM_INPUT):
        with open(SITE_GEOM_INPUT, "r") as f:
            site = json.load(f)
        ver = int(site.get("version", 0))
        if ver < 3 or "links" not in site:
            raise ValueError(
                "Existing /content/inputs/site_geometry.json is older schema (version<3).\n"
                "Delete it or set FORCE_RECLICK=True to rebuild."
            )
        print("[OK] Loaded site geometry from INPUTS:", SITE_GEOM_INPUT)
        _check_reachable_to_base(site, FLOORS_TO_USE, site.get("base_floor", BASE_FLOOR))
        return site, SITE_GEOM_INPUT

    # ----------------------------
    # 2) Otherwise load fallback if exists (outputs)
    # ----------------------------
    if (not FORCE_RECLICK) and os.path.exists(SITE_GEOM_FALLBACK):
        with open(SITE_GEOM_FALLBACK, "r") as f:
            site = json.load(f)
        ver = int(site.get("version", 0))
        if ver < 3 or "links" not in site:
            raise ValueError(
                "Existing output site_geometry.json is older schema (version<3).\n"
                "Delete it or set FORCE_RECLICK=True to rebuild."
            )
        print("[OK] Loaded site geometry from OUTPUTS:", SITE_GEOM_FALLBACK)
        _check_reachable_to_base(site, FLOORS_TO_USE, site.get("base_floor", BASE_FLOOR))
        return site, SITE_GEOM_FALLBACK

    # ----------------------------
    # 3) Create new via clicking (ANCHORS UNCHANGED)
    # ----------------------------
    if not IN_COLAB:
        print("[INFO] site_geometry.json not found; creating it now via interactive point picking...")

    site = {
        "version": 3,
        "master_esx_filename": os.path.basename(MASTER_ESX),
        "master_esx_sha256": sha256_file(MASTER_ESX),
        "base_floor": BASE_FLOOR,
        "links": {},               # child_floor -> {align_to, child_anchors_px, parent_anchors_px}
        "dut_px_by_floor": {},     # we will fill automatically (compat) after ESX parsing
        "dut_px_by_router": {},    # ✅ new: per-router DUTs
        "floor_elevation_m": {},   # optional for 3D
        "notes": "anchors are in floor image pixel coords; transforms built in meters; links can chain."
    }

    for f in FLOORS_TO_USE:
        if f == BASE_FLOOR:
            continue

        parent = ALIGN_TO_MAP.get(f, BASE_FLOOR)
        if parent not in FLOORS_META:
            raise ValueError(f"ALIGN_TO_MAP parent '{parent}' not found in FLOORS_META keys.")

        # 1) pick anchors on CHILD floor
        img_child = FLOORS_META[f]["img_path"]
        pts_child = pick_points(img_child, 2, f"[{f}] Click 2 anchors on THIS floor: (1) stair, (2) ref/corner")
        child_stair = [float(pts_child[0][0]), float(pts_child[0][1])]
        child_ref   = [float(pts_child[1][0]), float(pts_child[1][1])]

        # 2) pick matching anchors on PARENT floor (can differ per child)
        img_parent = FLOORS_META[parent]["img_path"]
        pts_parent = pick_points(
            img_parent, 2,
            f"[{parent}] Click the SAME 2 physical points matching '{f}' anchors: (1) stair, (2) ref/corner"
        )
        parent_stair = [float(pts_parent[0][0]), float(pts_parent[0][1])]
        parent_ref   = [float(pts_parent[1][0]), float(pts_parent[1][1])]

        site["links"][f] = {
            "align_to": parent,
            "labels": ["stair", "ref"],
            "child_anchors_px": {"stair_px": child_stair, "ref_px": child_ref},
            "parent_anchors_px": {"stair_px": parent_stair, "ref_px": parent_ref},
        }
        print(f"[OK] Link saved: {f} -> {parent}")

    _check_reachable_to_base(site, FLOORS_TO_USE, BASE_FLOOR)

    # Save to outputs path
    os.makedirs(os.path.dirname(SITE_GEOM_FALLBACK), exist_ok=True)
    with open(SITE_GEOM_FALLBACK, "w") as f:
        json.dump(site, f, indent=2)
    print("[OK] Created site geometry in OUTPUTS (anchors only):", SITE_GEOM_FALLBACK)

    # Optional: also copy into inputs for next runs (recommended)
    try:
        os.makedirs(INPUT_DIR, exist_ok=True)
        with open(SITE_GEOM_INPUT, "w") as f:
            json.dump(site, f, indent=2)
        print("[OK] Copied site geometry into INPUTS:", SITE_GEOM_INPUT)
        return site, SITE_GEOM_INPUT
    except Exception as e:
        print("[WARN] Could not copy site_geometry.json into INPUTS:", e)
        return site, SITE_GEOM_FALLBACK

# ------------------------------------------------------------
# DUT extraction from ESX (PER ROUTER)
# ------------------------------------------------------------
def _infer_router_key_from_filename(path: str) -> str:
    b = os.path.basename(path)
    # common pattern: "TMO-G5AR February 2026 Survey (No APs).esx"
    m = re.match(r"^([A-Za-z0-9_-]+)\s+", b)
    if m:
        return m.group(1)
    return os.path.splitext(b)[0]

def _read_esx_json(esx_path: str, member: str):
    with zipfile.ZipFile(esx_path, "r") as z:
        return json.loads(z.read(member).decode("utf-8"))

def _find_ap_placement_files(esx_path: str):
    with zipfile.ZipFile(esx_path, "r") as z:
        names = z.namelist()
    patt = re.compile(r"access.*(placement|location|position).*\.json$", re.IGNORECASE)
    return [n for n in names if patt.search(n)]

def _extract_xy_floor_from_obj(obj):
    """
    Recursively find dicts containing numeric x,y and (optional) floorPlanId.
    Returns list of (x,y,floorPlanId_or_None).
    """
    out = []
    def rec(o, inherited_floor=None):
        if isinstance(o, dict):
            floor = o.get("floorPlanId") or o.get("floorplanId") or o.get("floor_id") or inherited_floor
            if ("x" in o) and ("y" in o) and isinstance(o["x"], (int, float)) and isinstance(o["y"], (int, float)):
                out.append((float(o["x"]), float(o["y"]), floor))
            for _, v in o.items():
                rec(v, floor)
        elif isinstance(o, list):
            for v in o:
                rec(v, inherited_floor)
    rec(obj, None)
    return out

def extract_mine_ap_candidates(esx_path: str, base_floor_name: str):
    """
    Returns candidates list:
      [{ap_id, ap_name, floorPlanId, floorPlanName, x, y, metersPerUnit}]
    Only includes APs with mine:true and WITH coordinates (if present).
    """
    try:
        fp = _read_esx_json(esx_path, "floorPlans.json")["floorPlans"]
        fp_by_id = {f["id"]: f for f in fp}
    except Exception as e:
        print("[WARN] floorPlans.json missing/invalid in", os.path.basename(esx_path), ":", e)
        fp_by_id = {}

    try:
        aps = _read_esx_json(esx_path, "accessPoints.json")["accessPoints"]
    except Exception as e:
        print("[WARN] accessPoints.json missing/invalid in", os.path.basename(esx_path), ":", e)
        return []

    mine_aps = [ap for ap in aps if ap.get("mine") is True]
    if not mine_aps:
        return []

    placement_files = _find_ap_placement_files(esx_path)

    candidates = []
    for ap in mine_aps:
        ap_id = ap.get("id")
        ap_name = ap.get("name", "AP")

        # 1) try inside AP object
        xys = _extract_xy_floor_from_obj(ap)

        # 2) try external placement files (if any)
        if not xys and placement_files:
            for pf in placement_files:
                try:
                    data = _read_esx_json(esx_path, pf)
                except Exception:
                    continue
                # search for objects that mention this accessPointId
                hits = []
                def rec(o):
                    if isinstance(o, dict):
                        if o.get("accessPointId") == ap_id or o.get("access_point_id") == ap_id:
                            hits.append(o)
                        for v in o.values():
                            rec(v)
                    elif isinstance(o, list):
                        for v in o:
                            rec(v)
                rec(data)
                for h in hits:
                    xys.extend(_extract_xy_floor_from_obj(h))

        # keep only x,y with some floorPlanId found (if possible)
        best = None
        for (x, y, fpid) in xys:
            if fpid is not None:
                best = (x, y, fpid)
                break
        if best is None and xys:
            # no floorPlanId found, keep first
            best = xys[0]

        if best is None:
            continue

        x, y, fpid = best
        fpinfo = fp_by_id.get(fpid, {})
        floor_name = fpinfo.get("name", str(fpid))
        mpu = float(fpinfo.get("metersPerUnit", 1.0))

        candidates.append({
            "ap_id": ap_id,
            "ap_name": ap_name,
            "floorPlanId": fpid,
            "floorPlanName": floor_name,
            "x": float(x),
            "y": float(y),
            "metersPerUnit": mpu
        })

    # Prefer candidates that are on base floor by NAME match
    base_cands = [c for c in candidates if str(c["floorPlanName"]).strip().lower() == str(base_floor_name).strip().lower()]
    return base_cands if base_cands else candidates

def _dist_m(c1, c2):
    # compare in meters using each candidate metersPerUnit
    x1m = c1["x"] * c1.get("metersPerUnit", 1.0)
    y1m = c1["y"] * c1.get("metersPerUnit", 1.0)
    x2m = c2["x"] * c2.get("metersPerUnit", 1.0)
    y2m = c2["y"] * c2.get("metersPerUnit", 1.0)
    return float(np.hypot(x1m - x2m, y1m - y2m))

def choose_consistent_dut_per_router(router_to_candidates: dict, base_floor_name: str, max_iters: int = 8):
    """
    If a router has multiple mine:true candidates, choose the one minimizing
    average distance to other routers' chosen DUTs (on base floor if possible).
    """
    # Flatten all candidates to compute initial centroid (meters)
    all_pts = []
    for rk, cands in router_to_candidates.items():
        for c in cands:
            if str(c["floorPlanName"]).strip().lower() == str(base_floor_name).strip().lower():
                all_pts.append((c["x"]*c["metersPerUnit"], c["y"]*c["metersPerUnit"]))
    if not all_pts:
        # no base-floor candidates anywhere; use all
        for rk, cands in router_to_candidates.items():
            for c in cands:
                all_pts.append((c["x"]*c["metersPerUnit"], c["y"]*c["metersPerUnit"]))

    if all_pts:
        cx = float(np.mean([p[0] for p in all_pts]))
        cy = float(np.mean([p[1] for p in all_pts]))
    else:
        cx, cy = 0.0, 0.0

    # initial selection: closest-to-centroid
    selected = {}
    for rk, cands in router_to_candidates.items():
        if not cands:
            continue
        def score_to_centroid(c):
            xm, ym = c["x"]*c["metersPerUnit"], c["y"]*c["metersPerUnit"]
            return float(np.hypot(xm - cx, ym - cy))
        selected[rk] = min(cands, key=score_to_centroid)

    # iterative refinement: minimize mean distance to others
    for _ in range(max_iters):
        changed = False
        for rk, cands in router_to_candidates.items():
            if not cands:
                continue
            others = [selected[k] for k in selected.keys() if k != rk]
            if not others:
                continue

            def mean_dist(c):
                # only compare with others on same base floor name if possible
                dists = []
                for o in others:
                    if (str(c["floorPlanName"]).strip().lower() == str(base_floor_name).strip().lower() and
                        str(o["floorPlanName"]).strip().lower() == str(base_floor_name).strip().lower()):
                        dists.append(_dist_m(c, o))
                if not dists:
                    # fallback compare to all
                    dists = [_dist_m(c, o) for o in others]
                return float(np.mean(dists)) if dists else 1e18

            best = min(cands, key=mean_dist)
            if best["ap_id"] != selected[rk]["ap_id"]:
                selected[rk] = best
                changed = True
        if not changed:
            break
    return selected

def _get_router_esx_map():
    """
    Try to pull router ESX paths from existing globals.
    Falls back to scanning INPUT_DIR for *.esx excluding MASTER_ESX.
    """
    router_map = {}

    if "ROUTERS" in globals() and isinstance(ROUTERS, dict) and ROUTERS:
        for rk, info in ROUTERS.items():
            if isinstance(info, dict):
                p = info.get("esx_path") or info.get("path") or info.get("esx") or info.get("file")
                if p and os.path.exists(p):
                    router_map[str(rk)] = p
    if router_map:
        return router_map

    # fallback scan
    esx_files = sorted([p for p in glob.glob(os.path.join(INPUT_DIR, "*.esx"))])
    for p in esx_files:
        if os.path.basename(p) == os.path.basename(MASTER_ESX):
            continue
        rk = _infer_router_key_from_filename(p)
        router_map[rk] = p
    return router_map

# ------------------------------------------------------------
# Run: load/create anchors, then fill DUTs from ESX
# ------------------------------------------------------------
SITE, SITE_GEOM_PATH_USED = load_or_create_site_geometry()

BASE_FLOOR = SITE.get("base_floor", BASE_FLOOR)

missing_links = [f for f in FLOORS_TO_USE if f != BASE_FLOOR and f not in SITE.get("links", {})]
if missing_links:
    raise ValueError("Missing link entries for floors: " + ", ".join(missing_links))

print("[OK] Site geometry anchors ready. Loaded from:", SITE_GEOM_PATH_USED)
print("[OK] Links:", len(SITE.get("links", {})))

# ---- DUT PER ROUTER: extract from ESX JSON ----
router_esx_map = _get_router_esx_map()
print("[INFO] Router ESX files found:", len(router_esx_map))
for rk, p in router_esx_map.items():
    print("  -", rk, "->", os.path.basename(p))

# If already exists in SITE and not forcing, keep but fill missing routers
SITE.setdefault("dut_px_by_router", {})
SITE.setdefault("dut_px_by_floor", {})

need_extract = [rk for rk in router_esx_map.keys() if rk not in SITE["dut_px_by_router"]]
if need_extract:
    print("[INFO] Need DUT extraction for routers:", need_extract)

    router_to_candidates = {}
    for rk in need_extract:
        esx_path = router_esx_map[rk]
        cands = extract_mine_ap_candidates(esx_path, BASE_FLOOR)
        router_to_candidates[rk] = cands
        print(f"[INFO] {rk}: mine:true candidates with coords =", len(cands))
        for c in cands[:6]:
            print("   ", c["ap_name"], "| floor:", c["floorPlanName"], "| xy:", (round(c["x"],2), round(c["y"],2)))

    # choose consistent DUT per router (handles multiple mine:true)
    selected = choose_consistent_dut_per_router(router_to_candidates, BASE_FLOOR)

    for rk, c in selected.items():
        SITE["dut_px_by_router"][rk] = {
            "base_floor": BASE_FLOOR,
            "floorPlanId": c.get("floorPlanId"),
            "floorPlanName": c.get("floorPlanName"),
            "dut_px": [float(c["x"]), float(c["y"])],
            "source": {
                "esx_filename": os.path.basename(router_esx_map[rk]),
                "ap_id": c.get("ap_id"),
                "ap_name": c.get("ap_name"),
                "method": "mine_true_ap_position"
            }
        }
        print(f"[OK] DUT selected for {rk}: {c.get('ap_name')} @ ({c['x']:.2f},{c['y']:.2f}) on {c.get('floorPlanName')}")

# Backward compatibility: ensure dut_px_by_floor[BASE_FLOOR] exists
if BASE_FLOOR not in SITE["dut_px_by_floor"]:
    # Prefer MASTER router if available; else first router with dut
    preferred_rk = None
    if "ROUTERS" in globals() and isinstance(ROUTERS, dict):
        # try to prefer the master router key if you maintain one
        preferred_rk = next(iter(ROUTERS.keys()), None)

    if preferred_rk and preferred_rk in SITE["dut_px_by_router"]:
        SITE["dut_px_by_floor"][BASE_FLOOR] = SITE["dut_px_by_router"][preferred_rk]["dut_px"]
        print("[OK] dut_px_by_floor set from preferred router:", preferred_rk)
    else:
        any_rk = next(iter(SITE["dut_px_by_router"].keys()), None)
        if any_rk:
            SITE["dut_px_by_floor"][BASE_FLOOR] = SITE["dut_px_by_router"][any_rk]["dut_px"]
            print("[OK] dut_px_by_floor set from router:", any_rk)

# If still missing, optional click fallback
if (BASE_FLOOR not in SITE["dut_px_by_floor"]) and ALLOW_DUT_CLICK_FALLBACK:
    print("[WARN] Could not extract ANY DUT position from ESX JSON. Falling back to clicking once.")
    dut = pick_points(FLOORS_META[BASE_FLOOR]["img_path"], 1, f"[{BASE_FLOOR}] Click DUT position (fallback)")[0]
    SITE["dut_px_by_floor"][BASE_FLOOR] = [float(dut[0]), float(dut[1])]
    print("[OK] DUT fallback saved for base floor:", SITE["dut_px_by_floor"][BASE_FLOOR])

# Validate minimal requirement
if BASE_FLOOR not in SITE.get("dut_px_by_floor", {}):
    raise ValueError("Missing DUT for base floor. ESX did not contain placed mine:true AP coords and click fallback disabled.")

# Save updated SITE (anchors + DUTs)
try:
    with open(SITE_GEOM_PATH_USED, "w") as f:
        json.dump(SITE, f, indent=2)
    print("[OK] Updated site_geometry.json saved:", SITE_GEOM_PATH_USED)
except Exception as e:
    print("[WARN] Could not save updated site_geometry.json:", e)

print("[OK] DUT per router available in SITE['dut_px_by_router'] =", len(SITE.get("dut_px_by_router", {})))

"""## Build chained similarity transforms (floor → base) in meters"""

# =========================
# 9) Build similarity transforms (floor -> global(base)) in METERS
#    p_global = s*R*p_local + t
# =========================
def px_to_m(floor_name, xy_px):
    mpu = float(FLOORS_META[floor_name]["metersPerUnit"])
    return np.array([xy_px[0]*mpu, xy_px[1]*mpu], dtype=float)

def build_similarity_from_2pts(A1, A2, B1, B2):
    # A*,B* are 2D points in meters
    A1 = np.array(A1, float); A2=np.array(A2,float)
    B1 = np.array(B1, float); B2=np.array(B2,float)
    vA = A2 - A1
    vB = B2 - B1
    nA = np.linalg.norm(vA)
    nB = np.linalg.norm(vB)
    if nA < 1e-9 or nB < 1e-9:
        raise ValueError("Anchors too close; pick two distinct points.")
    s = nB / nA
    angA = np.arctan2(vA[1], vA[0])
    angB = np.arctan2(vB[1], vB[0])
    th = angB - angA
    c, si = np.cos(th), np.sin(th)
    R = np.array([[c, -si],[si, c]], float)
    t = B1 - (s * (R @ A1))
    return s, R, t

def apply_sim(p, s, R, t):
    p = np.array(p, float)
    return s*(R@p) + t

def invert_sim(p, s, R, t):
    p = np.array(p, float)
    return (R.T @ ((p - t)/s))

BASE_FLOOR = SITE["base_floor"]

# --- Handle chained transforms (recursive) ---
def get_full_transform(site_obj, target_floor, current_floor, current_s=1.0, current_R=np.eye(2), current_t=np.zeros(2)):
    if current_floor == target_floor:
        return {"s": current_s, "R": current_R, "t": current_t}

    link = site_obj["links"].get(current_floor)
    if not link:
        raise ValueError(f"No link found for floor '{current_floor}'. Cannot chain transform.")

    align_to_floor = link["align_to"]

    # Get anchors in meters
    mpu_child = float(FLOORS_META[current_floor]["metersPerUnit"])
    child_stair_m = np.array(link["child_anchors_px"]["stair_px"]) * mpu_child
    child_ref_m = np.array(link["child_anchors_px"]["ref_px"]) * mpu_child

    mpu_parent = float(FLOORS_META[align_to_floor]["metersPerUnit"])
    parent_stair_m = np.array(link["parent_anchors_px"]["stair_px"]) * mpu_parent
    parent_ref_m = np.array(link["parent_anchors_px"]["ref_px"]) * mpu_parent

    # Compute similarity transform from child to parent
    s_child_to_parent, R_child_to_parent, t_child_to_parent = build_similarity_from_2pts(
        child_stair_m, child_ref_m,
        parent_stair_m, parent_ref_m
    )

    # Combine with accumulated transform
    new_s = current_s * s_child_to_parent
    new_R = current_R @ R_child_to_parent
    new_t = current_s * (current_R @ t_child_to_parent) + current_t

    return get_full_transform(site_obj, target_floor, align_to_floor, new_s, new_R, new_t)

TRANSFORMS = {}
for f in FLOORS_TO_USE:
    if f == BASE_FLOOR:
        TRANSFORMS[f] = {"s":1.0, "R":np.eye(2), "t":np.zeros(2)}
        continue

    # Get transform from current floor to BASE_FLOOR
    tf_params = get_full_transform(SITE, BASE_FLOOR, f)
    TRANSFORMS[f] = tf_params
    print(f"[OK] Transform {f} -> {BASE_FLOOR}: scale={tf_params['s']:.6f}")

dut_base_px = SITE["dut_px_by_floor"][BASE_FLOOR]
DUT_GLOBAL_M = px_to_m(BASE_FLOOR, dut_base_px)

print("[INFO] DUT_GLOBAL_M:", DUT_GLOBAL_M)

"""## Sanity check (distance rings on each floor)"""

# =========================
# 10) Visual sanity-check: draw distance rings (ft) on each floor map
# =========================
RINGS_FT = [10, 20, 30, 40, 50, 60]
RINGS_DIR = os.path.join(OUT_BASE, "_distance_rings")
os.makedirs(RINGS_DIR, exist_ok=True)

def draw_rings_on_floor(floor_name: str):
    img_path = FLOORS_META[floor_name]["img_path"]
    img = cv2.imread(img_path)
    if img is None:
        raise FileNotFoundError(img_path)

    tf = TRANSFORMS[floor_name]
    dut_local_m = invert_sim(DUT_GLOBAL_M, tf["s"], tf["R"], tf["t"])
    mpu = float(FLOORS_META[floor_name]["metersPerUnit"])
    dut_local_px = (dut_local_m / mpu)

    cx, cy = int(round(dut_local_px[0])), int(round(dut_local_px[1]))
    cv2.circle(img, (cx, cy), 8, (0,0,255), -1)
    cv2.putText(img, "DUT(global)", (cx+10, cy-10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)

    for r_ft in RINGS_FT:
        r_m = r_ft / FEET_PER_METER
        r_local_m = r_m / tf["s"]
        r_px = int(round((r_local_m / mpu)))
        if r_px <= 0:
            continue
        cv2.circle(img, (cx, cy), r_px, (255,0,0), 2)
        cv2.putText(img, f"{r_ft}ft", (cx + r_px + 6, cy), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,0,0), 1)

    out_path = os.path.join(RINGS_DIR, f"{re.sub(r'[^A-Za-z0-9_-]+','_',floor_name)}_rings.png")
    cv2.imwrite(out_path, img)
    return out_path

ring_paths = []
for f in FLOORS_TO_USE:
    p = draw_rings_on_floor(f)
    ring_paths.append(p)
    print("[OK] Saved rings:", os.path.basename(p))

try:
    from IPython.display import Image as IPyImage
except Exception:
    IPyImage = None

if IPyImage is not None:
    for p in ring_paths:
        display(IPyImage(filename=p))
else:
    for p in ring_paths:
        print("[INFO] Ring preview saved:", p)

"""## Build curves from CSVs (distance bins)"""

# =========================
# 11) Load CSVs -> compute GLOBAL distance(ft) from Kitchen DUT -> build curves
# =========================
def compute_global_distance_ft(floor_name: str, cx_px: np.ndarray, cy_px: np.ndarray) -> np.ndarray:
    # Convert local floor pixels to global meters, then distance to DUT_GLOBAL_M.
    mpu = float(FLOORS_META[floor_name]["metersPerUnit"])
    pts_local_m = np.stack([cx_px*mpu, cy_px*mpu], axis=1)  # Nx2 in meters
    tf = TRANSFORMS[floor_name]
    pts_global_m = (tf["s"] * (pts_local_m @ tf["R"].T)) + tf["t"]  # Nx2
    dxy = pts_global_m - DUT_GLOBAL_M.reshape(1,2)
    d2 = (dxy[:,0]**2 + dxy[:,1]**2)

    if USE_3D:
        elev = SITE.get("floor_elevation_m", {})
        z = float(elev.get(floor_name, 0.0))
        z0 = float(elev.get(BASE_FLOOR, 0.0))
        d2 = d2 + (z - z0)**2

    return np.sqrt(d2) * FEET_PER_METER

def aggregate_by_distance(df: pd.DataFrame, bin_ft: float) -> pd.DataFrame:
    df = df.replace([np.inf, -np.inf], np.nan).dropna(subset=["distance_ft","value"])
    if df.empty:
        return pd.DataFrame()
    max_d = float(df["distance_ft"].max())
    edges = np.arange(0.0, max_d + bin_ft, bin_ft)
    if len(edges) < 2:
        edges = np.array([0.0, max_d + bin_ft])
    df = df.copy()
    df["bin"] = pd.cut(df["distance_ft"], bins=edges, include_lowest=True, right=False)

    g = df.groupby("bin", observed=True)["value"]
    def q(arr, p):
        return float(np.nanquantile(arr, p)) if len(arr) else np.nan

    mids = []
    for iv in g.groups.keys():
        mids.append(float(iv.left + (iv.right-iv.left)/2.0))

    out = pd.DataFrame({
        "dist_ft_mid": mids,
        "n": g.size().values,
        "mean": g.mean().values,
        "p50": g.median().values,
        "p10": g.apply(lambda s: q(s.values, 0.10)).values,
        "p90": g.apply(lambda s: q(s.values, 0.90)).values,
        "min": g.min().values,
        "max": g.max().values,
    })
    return out.sort_values("dist_ft_mid").reset_index(drop=True)


# ----------------------
# Curve aggregation cache (per CSV)
# ----------------------
def _jsonable_transforms(tfs: dict) -> dict:
    out = {}
    for k,v in tfs.items():
        out[k] = {
            "s": float(v["s"]),
            "R": [[float(v["R"][0,0]), float(v["R"][0,1])],[float(v["R"][1,0]), float(v["R"][1,1])]],
            "t": [float(v["t"][0]), float(v["t"][1])],
        }
    return out

def _geometry_signature() -> str:
    payload = {
        "PARAM_KEY": PARAM_KEY,
        "BIN_FT": float(BIN_FT),
        "USE_3D": bool(USE_3D),
        "BASE_FLOOR": BASE_FLOOR,
        "DUT_GLOBAL_M": [float(DUT_GLOBAL_M[0]), float(DUT_GLOBAL_M[1])],
        "SITE": SITE,  # json-safe
        "FLOORS_MPU": {f: float(FLOORS_META[f]["metersPerUnit"]) for f in FLOORS_TO_USE if f in FLOORS_META},
        "TRANSFORMS": _jsonable_transforms({f: TRANSFORMS[f] for f in FLOORS_TO_USE if f in TRANSFORMS}),
    }
    s = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(s.encode("utf-8")).hexdigest()

_GEO_SIG = _geometry_signature()

def _agg_cache_path(csv_path: str) -> str:
    csv_sha = _file_sha_cached(csv_path) if globals().get("CACHE_ENABLED", False) else sha256_file(csv_path)
    key = hashlib.sha256(f"{CACHE_VERSION}|agg|{_GEO_SIG}|{csv_sha}".encode("utf-8")).hexdigest()
    return os.path.join(CACHE_DIR, f"{CACHE_VERSION}__agg__{key}.pkl")


CURVES = []
errors = []

for _, r in META.iterrows():
    router_key = r["router_key"]
    floor = r["floor_name"]
    band = r["band"]
    csv_path = r["csv_path"]

    if floor not in FLOORS_META:
        errors.append(f"Floor not found in master: {floor} (csv={os.path.basename(csv_path)})")
        continue
    try:
        # Try cache (fast path)
        cache_fp = _agg_cache_path(csv_path) if globals().get("CACHE_ENABLED", False) else None
        if cache_fp and os.path.exists(cache_fp):
            agg = pd.read_pickle(cache_fp)
        else:
            df = pd.read_csv(csv_path)
            if not set(["cx","cy","value"]).issubset(df.columns):
                raise ValueError("CSV missing required columns: cx, cy, value")

            df = df.copy()
            df["distance_ft"] = compute_global_distance_ft(
                floor,
                df["cx"].astype(float).values,
                df["cy"].astype(float).values
            )
            agg = aggregate_by_distance(df, BIN_FT)

            if cache_fp and agg is not None and not agg.empty:
                try:
                    agg.to_pickle(cache_fp)
                except Exception as _e:
                    if globals().get("CACHE_VERBOSE", False):
                        print("[CACHE] write failed:", cache_fp, _e)

        if agg.empty:
            continue

        CURVES.append({
            "router_key": router_key,
            "router_display": ROUTERS.get(router_key, {}).get("display", router_key),
            "floor_name": floor,
            "band": band,
            "csv_path": csv_path,
            "agg": agg,
        })
        print(f"[OK] Curve built: {router_key} | {floor} | {band} | bins={len(agg)}")
    except Exception as e:
        errors.append(f"{os.path.basename(csv_path)}: {type(e).__name__}: {e}")

if errors:
    print("\n[WARN] Some files skipped:")
    for e in errors[:30]:
        print(" -", e)
    if len(errors) > 30:
        print(" ...", len(errors)-30, "more")

print("[INFO] Total curves:", len(CURVES))

"""## Optional debugging

### debugging missing curve
"""

### debugging missing curve
# Debugging why 'Sagemcom Living Room 2.4 GHz' curve was skipped

target_router_key = "Sagemcom"
target_floor = "Living Room"
target_band = "2.4GHz"

# Find the specific curve metadata from the META DataFrame
target_meta_row = META[
    (META["router_key"] == target_router_key) &
    (META["floor_name"] == target_floor) &
    (META["band"] == target_band)
]

if not target_meta_row.empty:
    r = target_meta_row.iloc[0] # Get the Series for this row
    csv_path = r["csv_path"]

    print(f"Investigating: {target_router_key} | {target_floor} | {target_band}")
    try:
        df_raw = pd.read_csv(csv_path)
        print(f"Raw CSV shape: {df_raw.shape}")

        if not set(["cx","cy","value"]).issubset(df_raw.columns):
            print("ERROR: CSV missing required columns: cx, cy, value")
        else:
            df_with_dist = df_raw.copy()
            # Re-using the functions defined earlier in the notebook to calculate distance
            # Note: compute_global_distance_ft, FLOORS_META, TRANSFORMS, and DUT_GLOBAL_M are global from earlier cells.
            df_with_dist["distance_ft"] = compute_global_distance_ft(target_floor, df_with_dist["cx"].astype(float).values, df_with_dist["cy"].astype(float).values)

            # Check for NaNs/Infs before dropping
            initial_rows = df_with_dist.shape[0]
            df_cleaned = df_with_dist.replace([np.inf, -np.inf], np.nan).dropna(subset=["distance_ft","value"])
            cleaned_rows = df_cleaned.shape[0]

            print(f"Rows before dropping NaNs/Infs: {initial_rows}")
            print(f"Rows after dropping NaNs/Infs in 'distance_ft' or 'value': {cleaned_rows}")

            if cleaned_rows == 0:
                print("\nCONCLUSION: The DataFrame for this combination became empty after dropping rows with NaN/Inf values. This is why the curve was skipped.")
                print("Displaying head and tail of the DataFrame before dropping invalid rows to show potential issues:")
                display(df_with_dist[['cx', 'cy', 'value', 'distance_ft']].head())
                display(df_with_dist[['cx', 'cy', 'value', 'distance_ft']].tail())
            else:
                print("Unexpected: Cleaned DataFrame is not empty. There might be another reason for skipping not covered by NaN/Inf drop.")

    except Exception as e:
        print(f"Error processing {os.path.basename(csv_path)}: {type(e).__name__}: {e}")
else:
    print(f"Could not find metadata for {target_router_key} | {target_floor} | {target_band} in the META DataFrame.")

"""## Save aggregated curve tables"""

# =========================
# 12) Save curve tables (long format)
# =========================
TABLE_DIR = os.path.join(OUT_BASE, "tables")
os.makedirs(TABLE_DIR, exist_ok=True)

rows = []
for c in CURVES:
    a = c["agg"].copy()
    a["router_key"] = c["router_key"]
    a["router_display"] = c["router_display"]
    a["floor_name"] = c["floor_name"]
    a["band"] = c["band"]
    a["raw_csv"] = os.path.basename(c["csv_path"])
    rows.append(a)

ALL_TABLE = pd.concat(rows, ignore_index=True) if rows else pd.DataFrame()
table_path = os.path.join(TABLE_DIR, f"{PARAM_KEY}_curve_tables.csv")
ALL_TABLE.to_csv(table_path, index=False)
print("[OK] Saved:", table_path)
display(ALL_TABLE.head(20))

"""## Plotting

### gemini debugging (percentage calculation on overall average).

### Plotting utilities (shared)

This cell defines shared helper functions used by the plotting cells to avoid duplication.
"""

# Shared plotting helpers (used by both percent + actual plots)
import json, re
import numpy as np
import matplotlib.pyplot as plt

def uniq(seq):
    seen=set(); out=[]
    for x in seq:
        if x not in seen:
            out.append(x); seen.add(x)
    return out

def pad_limits(vmin, vmax, frac=0.06):
    if not np.isfinite(vmin) or not np.isfinite(vmax):
        return (0.0, 1.0)
    if vmax == vmin:
        return (vmin - 1.0, vmax + 1.0)
    span = vmax - vmin
    return (vmin - frac*span, vmax + frac*span)

def save_plot_with_meta(fig, ax, png_path, meta_path):
    fig.canvas.draw()
    W, H = fig.canvas.get_width_height()
    bbox = ax.get_window_extent()
    meta = {
        'image_w': int(W),
        'image_h': int(H),
        'ax_bbox': {
            'left': float(bbox.x0),
            'bottom': float(bbox.y0),
            'right': float(bbox.x1),
            'top': float(bbox.y1),
        }
    }
    fig.savefig(png_path, dpi=150, bbox_inches='tight')
    with open(meta_path, 'w', encoding='utf-8') as f:
        json.dump(meta, f)

def to_percent(values: np.ndarray, higher_is_better: bool, mode: str):
    v = values.astype(float)
    v = v[np.isfinite(v)]
    if len(v) == 0:
        return None
    vmin, vmax = float(np.min(v)), float(np.max(v))
    if vmax == vmin:
        return (vmin, vmax, lambda arr: np.full_like(arr, 100.0, dtype=float))
    if mode == 'max' and vmax > 0:
        def f(arr):
            p = 100.0 * (arr / vmax)
            return np.clip(p, 0, 100)
    else:
        def f(arr):
            p = 100.0 * (arr - vmin) / (vmax - vmin)
            return np.clip(p, 0, 100)
    if not higher_is_better:
        return (vmin, vmax, lambda arr: 100.0 - f(arr))
    return (vmin, vmax, f)

def _safe_slug(s: str) -> str:
    return re.sub(r'[^A-Za-z0-9_-]+', '_', str(s))

def _router_name_only(router_key: str, router_display: str = "") -> str:
    if router_key:
        return str(router_key)
    s = str(router_display or "")
    s = re.sub(r"\s*February\s*\d{4}.*$", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\s*Survey.*$", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\.esx$", "", s, flags=re.IGNORECASE) # Remove .esx if still present
    s = s.strip(" -_")
    return s if s else "ROUTER"

def _legend_cols(n: int) -> int:
    if n <= 6: return 1
    if n <= 12: return 2
    return 3

def _fmt_pct_per_ft(v: float) -> str:
    if not np.isfinite(v):
        return 'n/a'
    return f"{v:.2f}%/ft"

def _prepend_zero_point(x, y, method='linear', clip_0_100=True, clamp_to_minmax=False):
    x = np.asarray(x, float)
    y = np.asarray(y, float)
    if len(x) == 0:
        return x, y
    order = np.argsort(x)
    x = x[order]
    y = y[order]
    if x[0] <= 1e-9:
        if clip_0_100:
            y = np.clip(y, 0, 100)
        return x, y
    if method == 'linear' and len(x) >= 2 and (x[1] - x[0]) != 0:
        y0 = y[0] + (0.0 - x[0]) * (y[1] - y[0]) / (x[1] - x[0])
    else:
        y0 = y[0]
    if clamp_to_minmax:
        y0 = float(np.clip(y0, float(np.nanmin(y)), float(np.nanmax(y))))
    x2 = np.concatenate([[0.0], x])
    y2 = np.concatenate([[y0], y])
    if clip_0_100:
        y2 = np.clip(y2, 0, 100)
    return x2, y2

def compute_avg_drop_per_ft_from_xy(x, y) -> float:
    x = np.asarray(x, float)
    y = np.asarray(y, float)
    if len(x) < 2:
        return np.nan
    order = np.argsort(x)
    x = x[order]
    y = y[order]
    dx = np.diff(x)
    dy = np.diff(y)
    m = (dx > 1e-9) & np.isfinite(dx) & np.isfinite(dy)
    if not np.any(m):
        return np.nan
    # drop per ft (positive when y decreases)
    return float(np.nanmean(-dy[m] / dx[m]))

def _is_pct_like(unit: str) -> bool:
    u = str(unit).strip()
    return u == '%' or u.lower() in ['percent', 'percentage']

def pick_actual_y_col(agg_df, y_stat: str):
    # Prefer y_stat if present, else fall back
    if agg_df is None or len(agg_df) == 0:
        return None
    if y_stat in agg_df.columns:
        return y_stat
    for c in ['p50','mean','p90','p10','max','min']:
        if c in agg_df.columns:
            return c
    return None

# =========================
# 14A) Plotting (Percent) — COMPARE ROUTERS BY FLOOR
# + Sort routers by OVERALL AVG PERCENT (best→worst)
# + AVG DROP COMMENTED OUT
# =========================
import os, re, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl # Added for global config initialization

PLOTS_DIR_PCT = os.path.join(OUT_BASE, "plots_percent")
os.makedirs(PLOTS_DIR_PCT, exist_ok=True)

try:
    import matplotlib.patheffects as pe
    _HAS_PE = True
except Exception:
    _HAS_PE = False


ZERO_INSERT_METHOD = "linear"

# (shared helpers are defined in the Plotting utilities cell above)

# --- Global Plotting Config ---
router_keys = sorted(uniq([c["router_key"] for c in CURVES]))
floor_names = sorted(uniq([c["floor_name"] for c in CURVES]))

base_colors = mpl.rcParams["axes.prop_cycle"].by_key().get("color", [])
if len(base_colors) < len(router_keys):
    cmap = plt.get_cmap("tab20")
    base_colors = [cmap(i) for i in range(max(20, len(router_keys)))]
COLOR_BY_ROUTER = {rk: base_colors[i % len(base_colors)] for i, rk in enumerate(router_keys)}

ROUTER_LINESTYLES = ["-", "--", ":", "-."]  # solid, dashed, dotted, dashdot
ROUTER_MARKERS = ["o","s","D","^","v","P","X","*","<",">"]

STYLE_BY_ROUTER  = {rk: ROUTER_LINESTYLES[i % len(ROUTER_LINESTYLES)] for i, rk in enumerate(router_keys)}
MARKER_BY_ROUTER = {rk: ROUTER_MARKERS[i % len(ROUTER_MARKERS)] for i, rk in enumerate(router_keys)}

LINEWIDTH = 2.2
ALPHA = 0.92
OUTLINE = True
OUTLINE_WIDTH = 4.0
OUTLINE_COLOR = "white"
LEGEND_FONTSIZE = 8

# How to create the y-value at x=0 if first sample starts at x>0
# This variable was already defined in the first code block, so we'll just keep it here.
# ZERO_INSERT_METHOD = "linear"

def plot_floor_routers_percent(curves, band: str, floor_name: str, out_png: str,
                               router_order: list,
                               avg_perf_by_router: dict):
    fig, ax = plt.subplots(figsize=(10, 6))
    curves_by_rk = {c["router_key"]: c for c in curves}
    ordered = [curves_by_rk[rk] for rk in router_order if rk in curves_by_rk]

    used_x, used_y = [], []
    for i, c in enumerate(ordered):
        rk = c["router_key"]
        a = c["agg"]
        vals = a[Y_STAT].values.astype(float)
        res = to_percent(vals, HIGHER_IS_BETTER, PERCENT_MODE)
        if res is None: continue
        map_fn = res[2]

        x = a["dist_ft_mid"].values.astype(float)
        y = map_fn(vals)
        x, y = _prepend_zero_point(x, y, method=ZERO_INSERT_METHOD, clip_0_100=True)

        used_x.append(x); used_y.append(y)
        color = COLOR_BY_ROUTER.get(rk)
        ls = STYLE_BY_ROUTER.get(rk, "-")

        rname = _router_name_only(rk, c.get("router_display", ""))
        # Updated Label: Show Avg Performance instead of Drop
        label = f"{rname} | avg: {avg_perf_by_router.get(rk, 0):.1f}%"
        # label += f" | drop: {_fmt_pct_per_ft(drop_perft_by_router.get(rk, np.nan))}" # COMMENTED OUT

        line, = ax.plot(x, y, color=color, linestyle=ls, linewidth=LINEWIDTH, alpha=ALPHA, label=label, zorder=2+i)
        if _HAS_PE and OUTLINE:
            line.set_path_effects([pe.Stroke(linewidth=OUTLINE_WIDTH, foreground=OUTLINE_COLOR), pe.Normal()])

    ax.set_title(f"{PARAM_PRETTY} (%) — {band} — Floor: {floor_name}")
    ax.set_xlabel("Distance from DUT (ft)"); ax.set_ylabel("Performance (%)")
    ax.grid(True, alpha=0.22)
    if used_x:
        ax.legend(loc="best", fontsize=LEGEND_FONTSIZE, ncols=_legend_cols(len(used_x)), frameon=True)
        all_x, all_y = np.concatenate(used_x), np.concatenate(used_y)
        _, xmax = pad_limits(0, float(np.nanmax(all_x)), 0.04)
        ymin, ymax = pad_limits(float(np.nanmin(all_y)), float(np.nanmax(all_y)), 0.08)
        ax.set_xlim(left=0.0, right=xmax); ax.set_ylim(bottom=ymin, top=ymax)

    fig.tight_layout()
    save_plot_with_meta(fig, ax, out_png, out_png.replace(".png", ".meta.json"))
    plt.show() # Inline plotting enabled
    return out_png

# --- Run Logic ---
for band in BANDS:
    band_curves = [c for c in CURVES if c["band"] == band]
    for fn in sorted(set([c["floor_name"] for c in band_curves])):
        fc = [c for c in band_curves if c["floor_name"] == fn]
        avg_perf_by_router = {}

        for c in fc:
            rk = c["router_key"]
            vals = c["agg"][Y_STAT].values.astype(float)
            res = to_percent(vals, HIGHER_IS_BETTER, PERCENT_MODE)
            if res:
                y_pct = res[2](vals)
                avg_perf_by_router[rk] = np.nanmean(y_pct)

        # Sort by avg performance descending (best to worst)
        router_order = sorted(avg_perf_by_router.keys(), key=lambda rk: avg_perf_by_router[rk], reverse=True)

        out_png = os.path.join(PLOTS_DIR_PCT, "COMPARE_ROUTERS_BY_FLOOR", f"{PARAM_KEY}__pct__{band}__floor_{_safe_slug(fn)}.png")
        os.makedirs(os.path.dirname(out_png), exist_ok=True)
        plot_floor_routers_percent(fc, band, fn, out_png, router_order, avg_perf_by_router)

# =========================
# 14B) Plotting (Percent) — COMPARE FLOORS BY ROUTER (per band)
# + Sort floors in legend by OVERALL AVG PERCENT
# + AVG DROP COMMENTED OUT
# =========================
import os, re, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl # Added for global config initialization

PLOTS_DIR_PCT = os.path.join(OUT_BASE, "plots_percent")
os.makedirs(PLOTS_DIR_PCT, exist_ok=True)

try:
    import matplotlib.patheffects as pe
    _HAS_PE = True
except Exception:
    _HAS_PE = False

# (shared helpers are defined in the Plotting utilities cell above)

# --- Global Plotting Config (Floor-specific) ---
router_keys = sorted(uniq([c["router_key"] for c in CURVES]))
floor_names = sorted(uniq([c["floor_name"] for c in CURVES]))

base_colors_general = mpl.rcParams["axes.prop_cycle"].by_key().get("color", [])
if len(base_colors_general) < len(floor_names):
    cmap_floor = plt.get_cmap("tab20")
    base_colors_general = [cmap_floor(i) for i in range(max(len(floor_names), 20))]
COLOR_BY_FLOOR = {fn: base_colors_general[i % len(base_colors_general)] for i, fn in enumerate(floor_names)}

LINESTYLES = ["-", "--", "-.", ":"]
MARKERS = ["o","s","D","^","v","P","X","*","<",">"]
STYLE_BY_FLOOR  = {fn: LINESTYLES[i % len(LINESTYLES)] for i, fn in enumerate(floor_names)}
MARKER_BY_FLOOR = {fn: MARKERS[i % len(MARKERS)] for i, fn in enumerate(floor_names)}

LINEWIDTH = 2.2
ALPHA = 0.92
OUTLINE = True
OUTLINE_WIDTH = 4.0
OUTLINE_COLOR = "white"
LEGEND_FONTSIZE = 8
MARKERS_TARGET = 22


def plot_router_floors_percent(curves, band: str, router_key: str, router_display: str, out_png: str):
    # First, calculate individual curve averages for sorting the legend
    stats = []
    for c in curves:
        a = c["agg"]
        vals = a[Y_STAT].values.astype(float)
        res = to_percent(vals, HIGHER_IS_BETTER, PERCENT_MODE)
        if res:
            y_pct = res[2](vals)
            stats.append({'curve': c, 'avg': np.nanmean(y_pct), 'map_fn': res[2]})

    # Sort stats list: Highest average first
    stats = sorted(stats, key=lambda x: x['avg'], reverse=True)

    fig, ax = plt.subplots(figsize=(10, 6))
    used_x, used_y = [], []

    for i, item in enumerate(stats):
        c = item['curve']
        map_fn = item['map_fn']
        avg_val = item['avg']
        a = c["agg"]
        fn = c["floor_name"]

        x = a["dist_ft_mid"].values.astype(float)
        y = map_fn(a[Y_STAT].values.astype(float))
        x, y = _prepend_zero_point(x, y, method=ZERO_INSERT_METHOD, clip_0_100=True)

        used_x.append(x); used_y.append(y)
        color = COLOR_BY_FLOOR.get(fn)
        ls = STYLE_BY_FLOOR.get(fn, "-")

        line, = ax.plot(x, y, color=color, linestyle=ls, linewidth=LINEWIDTH, alpha=ALPHA,
                label=f"{fn} | avg: {avg_val:.1f}%", zorder=2+i)

        if _HAS_PE and OUTLINE:
            line.set_path_effects([pe.Stroke(linewidth=OUTLINE_WIDTH, foreground=OUTLINE_COLOR), pe.Normal()])

    short_router = _router_name_only(router_key, router_display)
    ax.set_title(f"{PARAM_PRETTY} (%) — {band} — Router: {short_router}")
    ax.set_xlabel("Distance from DUT (ft)"); ax.set_ylabel("Performance (%)")
    ax.grid(True, alpha=0.22)

    if stats:
        ax.legend(loc="best", fontsize=LEGEND_FONTSIZE, ncols=_legend_cols(len(stats)), frameon=True)
        all_x, all_y = np.concatenate(used_x), np.concatenate(used_y)
        _, xmax = pad_limits(0, float(np.nanmax(all_x)), 0.04)
        ymin, ymax = pad_limits(float(np.nanmin(all_y)), float(np.nanmax(all_y)), 0.08)
        ax.set_xlim(left=0.0, right=xmax); ax.set_ylim(bottom=ymin, top=ymax)

    fig.tight_layout()
    save_plot_with_meta(fig, ax, out_png, out_png.replace(".png", ".meta.json"))
    plt.show() # Inline plotting enabled
    return out_png

# --- Run Logic ---
saved_pct_router_floors = []

for band in BANDS:
    band_curves = [c for c in CURVES if c["band"] == band]
    if not band_curves: continue

    for rk in sorted(set([c["router_key"] for c in band_curves])):
        rc = [c for c in band_curves if c["router_key"] == rk]
        if not rc: continue

        out_png = os.path.join(PLOTS_DIR_PCT, "COMPARE_FLOORS_BY_ROUTER", f"{PARAM_KEY}__pct__{band}__router_{rk}.png")
        os.makedirs(os.path.dirname(out_png), exist_ok=True)
        saved_pct_router_floors.append(
            plot_router_floors_percent(rc, band, rk, rc[0].get("router_display", rk), out_png)
        )

print("[INFO] Total saved (percent, floors-by-router):", len(saved_pct_router_floors))

"""### graph on actual value using overall average value ( like overall datarate, signal strength, throughput, sn, etc.)."""

# =========================
# 14A-ACTUAL) Plotting (Actual) — COMPARE ROUTERS BY FLOOR (per band)
# + Legend: ROUTER | avg: XX.X <unit>
# + Sort routers by avg (best→worst)
# + Interpolate/prepend a point at 0 ft so curves start from DUT
# + FIX: clamp synthetic 0-ft y0 to CSV-derived [min(y), max(y)]
# =========================
import os, re, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl # Added for global config initialization

PLOTS_DIR_ACT = os.path.join(OUT_BASE, "plots_actual")
os.makedirs(PLOTS_DIR_ACT, exist_ok=True)

try:
    import matplotlib.patheffects as pe
    _HAS_PE = True
except Exception:
    _HAS_PE = False

# --- Global Configs & Helper Functions (for self-containment) ---
def uniq(seq):
    seen=set(); out=[]
    for x in seq:
        if x not in seen:
            out.append(x); seen.add(x)
    return out

# Global Plotting Config (re-initialized for this cell's self-containment)
router_keys = sorted(list(set([c["router_key"] for c in CURVES])))
floor_names = sorted(list(set([c["floor_name"] for c in CURVES])))

base_colors = mpl.rcParams["axes.prop_cycle"].by_key().get("color", [])
if len(base_colors) < len(router_keys):
    cmap = plt.get_cmap("tab20")
    base_colors = [cmap(i) for i in range(max(20, len(router_keys)))]
COLOR_BY_ROUTER = {rk: base_colors[i % len(base_colors)] for i, rk in enumerate(router_keys)}

if len(base_colors) < len(floor_names):
    cmap_floor = plt.get_cmap("tab20")
    base_colors_floor = [cmap_floor(i) for i in range(max(len(floor_names), 20))]
else:
    base_colors_floor = base_colors
COLOR_BY_FLOOR = {fn: base_colors_floor[i % len(base_colors_floor)] for i, fn in enumerate(floor_names)}

ROUTER_LINESTYLES = ["-", "--", ":", "-."]
ROUTER_MARKERS = ["o","s","D","^","v","P","X","*","<",">"]
STYLE_BY_ROUTER  = {rk: ROUTER_LINESTYLES[i % len(ROUTER_LINESTYLES)] for i, rk in enumerate(router_keys)}
MARKER_BY_ROUTER = {rk: ROUTER_MARKERS[i % len(ROUTER_MARKERS)] for i, rk in enumerate(router_keys)}

LINESTYLES = ["-", "--", "-.", ":"]
MARKERS = ["o","s","D","^","v","P","X","*","<",">"]
STYLE_BY_FLOOR  = {fn: LINESTYLES[i % len(LINESTYLES)] for i, fn in enumerate(floor_names)}
MARKER_BY_FLOOR = {fn: MARKERS[i % len(MARKERS)] for i, fn in enumerate(floor_names)}

LINEWIDTH = 2.2
ALPHA = 0.92
OUTLINE = True
OUTLINE_WIDTH = 4.0
OUTLINE_COLOR = "white"
LEGEND_FONTSIZE = 8
MARKERS_TARGET = 22 # Not used in this particular plotting function but good to include for consistency


def pad_limits(vmin, vmax, frac=0.06):
    if not np.isfinite(vmin) or not np.isfinite(vmax):
        return (0.0, 1.0)
    if vmax == vmin:
        return (vmin - 1.0, vmax + 1.0)
    span = vmax - vmin
    return (vmin - frac*span, vmax + frac*span)

def save_plot_with_meta(fig, ax, png_path, meta_path):
    fig.canvas.draw()
    W, H = fig.canvas.get_width_height()
    bbox = ax.get_window_extent()
    meta = {
        "image_w": int(W),
        "image_h": int(H),
        "ax_bbox": {
            "left": float(bbox.x0),
            "right": float(bbox.x1),
            "top": float(H - bbox.y1),
            "bottom": float(H - bbox.y0),
        },
        "xlim": list(map(float, ax.get_xlim())),
        "ylim": list(map(float, ax.get_ylim())),
    }
    fig.savefig(png_path, dpi=200)
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)

def _legend_cols(n: int) -> int:
    if n <= 6: return 1
    if n <= 14: return 2
    return 3

def _safe_slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_-]+", "_", str(s))[:80]

def _router_name_only(router_key: str, router_display: str = "") -> str:
    if router_key:
        return str(router_key)
    s = str(router_display or "")
    s = re.sub(r"\s*February\s*\d{4}.*$", "", s, flags=re.IGNORECASE)
    s = re.sub(r"\s*Survey.*$", "", s, flags=re.IGNORECASE)
    s = s.strip(" -_")
    return s if s else "ROUTER"

UNIT_LABEL = globals().get("PARAM_UNIT", "").strip()
UNIT_SUFFIX = f" {UNIT_LABEL}/ft" if UNIT_LABEL else "/ft"


# The problematic function - corrected and included
CLAMP_ZERO_TO_DATA_RANGE = True # Global config for this section

def _prepend_zero_point(x, y, method="linear", clamp_to_data=True):
    """
    Prepend a point at x=0. If method='linear', extrapolation can overshoot.
    clamp_to_data=True clamps y0 to [min(y), max(y)] so it never exceeds CSV-derived range.
    """
    x = np.asarray(x, float)
    y = np.asarray(y, float)
    if len(x) == 0:
        return x, y

    order = np.argsort(x)
    x = x[order]
    y = y[order]

    if x[0] <= 1e-9:
        return x, y

    if method == "linear" and len(x) >= 2 and (x[1] - x[0]) != 0:
        y0 = y[0] + (0.0 - x[0]) * (y[1] - y[0]) / (x[1] - x[0])
    else:
        y0 = y[0]  # flat

    if clamp_to_data:
        finite = np.isfinite(y)
        if np.any(finite):
            ymin = float(np.nanmin(y[finite]))
            ymax = float(np.nanmax(y[finite]))
            y0 = float(np.clip(y0, ymin, ymax))

    return np.concatenate([[0.0], x]), np.concatenate([[y0], y])


def _is_pct_like(name: str) -> bool:
    s = str(name).lower()
    return ("pct" in s) or ("percent" in s) or s.endswith("%")

def pick_actual_y_col(df: pd.DataFrame, y_stat: str) -> str:
    """
    Choose a likely RAW/ACTUAL column (avoid percent columns).
    Priority:
      1) y_stat if present and not pct-like
      2) common raw columns
      3) fallback: first numeric non-pct column
    """
    cols = list(df.columns)
    cols_set = set(cols)
    y_stat = str(y_stat)

    # If y_stat exists and doesn't look like percent, use it
    if y_stat in cols_set and not _is_pct_like(y_stat):
        return y_stat

    # Common raw column names in your pipeline(s)
    for c in ["metric_p50", "p50", "value_p50", "metric", "value", "mean", "metric_mean"]:
        if c in cols_set and not _is_pct_like(c):
            return c

    # If y_stat exists but looks percent, try stripping suffixes
    if y_stat in cols_set and _is_pct_like(y_stat):
        base = re.sub(r"(_pct|_percent|%)+$", "", y_stat, flags=re.IGNORECASE)
        if base in cols_set and not _is_pct_like(base):
            return base

    # fallback: first numeric non-pct column
    for c in cols:
        if _is_pct_like(c):
            continue
        if pd.api.types.is_numeric_dtype(df[c]):
            return c

    # last resort
    return y_stat
# --- End Helper Functions ---

# --- Run Logic ---
def plot_floor_routers_actual(curves, band: str, floor_name: str, out_png: str,
                             router_order: list, avg_perf_by_router: dict, y_col_by_router: dict):
    fig, ax = plt.subplots(figsize=(10, 6))

    curves_by_rk = {c["router_key"]: c for c in curves}
    ordered = [curves_by_rk[rk] for rk in router_order if rk in curves_by_rk]

    used_x, used_y = [], []
    unit_str = f" {UNIT_LABEL}" if UNIT_LABEL else ""

    for i, c in enumerate(ordered):
        rk = c["router_key"]
        a = c["agg"]
        ycol = y_col_by_router.get(rk, Y_STAT)

        x = a["dist_ft_mid"].values.astype(float)
        y = a[ycol].values.astype(float)
        x, y = _prepend_zero_point(x, y, method=ZERO_INSERT_METHOD, clamp_to_data=CLAMP_ZERO_TO_DATA_RANGE)

        used_x.append(x)
        used_y.append(y)

        color = COLOR_BY_ROUTER.get(rk, None)
        ls = STYLE_BY_ROUTER.get(rk, "-") if "STYLE_BY_ROUTER" in globals() else "-"

        rname = _router_name_only(rk, c.get("router_display", ""))

        # Updated Label: Show Avg instead of Drop
        avg_val = avg_perf_by_router.get(rk, np.nan)
        label = f"{rname} | avg: {avg_val:.1f}{unit_str}"

        line, = ax.plot(x, y, color=color, linestyle=ls, linewidth=LINEWIDTH, alpha=ALPHA, label=label, zorder=2 + i)
        if _HAS_PE and OUTLINE:
            line.set_path_effects([pe.Stroke(linewidth=OUTLINE_WIDTH, foreground=OUTLINE_COLOR), pe.Normal()])

        if FILL_SPREAD and ("p10" in a.columns) and ("p90" in a.columns) and (ycol == Y_STAT):
            y10 = a["p10"].values.astype(float)
            y90 = a["p90"].values.astype(float)
            _, y10 = _prepend_zero_point(a["dist_ft_mid"].values.astype(float), y10, method=ZERO_INSERT_METHOD, clamp_to_data=True)
            _, y90 = _prepend_zero_point(a["dist_ft_mid"].values.astype(float), y90, method=ZERO_INSERT_METHOD, clamp_to_data=True)
            ax.fill_between(x, y10, y90, alpha=0.10, color=color, zorder=1)

    ylabel = f"{PARAM_PRETTY} ({UNIT_LABEL})" if UNIT_LABEL else f"{PARAM_PRETTY}"
    ax.set_title(f"{PARAM_PRETTY} (Actual) — {band} — Floor: {floor_name} (routers)")
    ax.set_xlabel("Distance from DUT (ft)")
    ax.set_ylabel(ylabel)
    ax.grid(True, alpha=0.22)

    if used_x:
        ax.legend(loc="best", fontsize=LEGEND_FONTSIZE, ncols=_legend_cols(len(used_x)), frameon=True, framealpha=0.85)
        all_x, all_y = np.concatenate(used_x), np.concatenate(used_y)
        xmin, xmax = pad_limits(float(np.nanmin(all_x)), float(np.nanmax(all_x)), 0.04)
        ymin, ymax = pad_limits(float(np.nanmin(all_y)), float(np.nanmax(all_y)), 0.08)
        ax.set_xlim(left=0.0, right=xmax)
        ax.set_ylim(bottom=ymin, top=ymax)

    fig.tight_layout()
    meta_path = out_png.replace(".png", ".meta.json")
    save_plot_with_meta(fig, ax, out_png, meta_path)
    plt.show() # Inline plotting left active
    print("[OK] Saved:", out_png)
    return (out_png, meta_path)

# ------------------------- Main: plot per band + per floor -------------------------
saved_act_floor_routers = []

for band in BANDS:
    band_curves = [c for c in CURVES if c["band"] == band]
    if not band_curves: continue

    for fn in sorted(set([c["floor_name"] for c in band_curves])):
        fc = [c for c in band_curves if c["floor_name"] == fn]
        if not fc: continue

        avg_perf_by_router = {}
        y_col_by_router = {}

        for c in fc:
            rk = c["router_key"]
            a = c["agg"]
            ycol = pick_actual_y_col(a, Y_STAT)
            y_col_by_router[rk] = ycol

            vals = pd.to_numeric(a[ycol], errors="coerce").to_numpy(dtype=float)

            # Replaced drop with simple overall average
            avg_perf_by_router[rk] = float(np.nanmean(vals))

        router_keys = [c["router_key"] for c in fc]

        # Sort based on HIGHER_IS_BETTER
        if HIGHER_IS_BETTER:
            router_order = sorted(router_keys, key=lambda rk: avg_perf_by_router.get(rk, -np.inf), reverse=True)
        else:
            router_order = sorted(router_keys, key=lambda rk: avg_perf_by_router.get(rk, np.inf))

        # Ranking CSV Updated to save Avg Actual instead of Avg Drop
        rank_csv = os.path.join(PLOTS_DIR_ACT, "COMPARE_ROUTERS_BY_FLOOR", f"{PARAM_KEY}__act__{band}__floor_{_safe_slug(fn)}__avg_actual.csv")
        os.makedirs(os.path.dirname(rank_csv), exist_ok=True)
        pd.DataFrame([{
            "router_key": rk,
            "router_name": _router_name_only(rk, ROUTERS.get(rk, {}).get("display", rk)),
            "band": band,
            "floor": fn,
            "y_col_used": y_col_by_router.get(rk, Y_STAT),
            "avg_actual": avg_perf_by_router.get(rk, np.nan),
            "unit": UNIT_LABEL,
            "rank_best_to_worst": i+1
        } for i, rk in enumerate(router_order)]).to_csv(rank_csv, index=False)

        safe_floor = _safe_slug(fn)
        out_png = os.path.join(PLOTS_DIR_ACT, "COMPARE_ROUTERS_BY_FLOOR", f"{PARAM_KEY}__act__{band}__floor_{safe_floor}.png")
        os.makedirs(os.path.dirname(out_png), exist_ok=True)

        saved_act_floor_routers.append(
            plot_floor_routers_actual(fc, band, fn, out_png, router_order, avg_perf_by_router, y_col_by_router)
        )

print("[INFO] Total saved (actual, routers-by-floor):", len(saved_act_floor_routers))

# =========================
# 14B-ACTUAL) Plotting (Actual) — COMPARE FLOORS BY ROUTER (per band)
# + Sort floors in legend by OVERALL AVG
# + Interpolate/prepend a point at 0 ft so curves start from DUT
# + FIX: clamp synthetic 0-ft y0 to CSV-derived [min(y), max(y)]
# =========================
import os, re, json
import numpy as np
import matplotlib.pyplot as plt

PLOTS_DIR_ACT = os.path.join(OUT_BASE, "plots_actual")
os.makedirs(PLOTS_DIR_ACT, exist_ok=True)

try:
    import matplotlib.patheffects as pe
    _HAS_PE = True
except Exception:
    _HAS_PE = False

# ... [Keep your Global Configs & Helpers (limits, zero-prepend) exactly the same] ...

# ------------------------- Drop computation commented out -------------------------
# def compute_avg_drop_per_ft_from_xy(x, y, higher_is_better: bool):
#     ... [Original drop computation logic] ...
#     return float((near_perf - far_perf) / dft)

def plot_router_floors_actual(curves, band: str, router_key: str, router_display: str, out_png: str):
    fig, ax = plt.subplots(figsize=(10, 6))

    # Pre-calculate data and averages for sorting
    stats = []
    for c in curves:
        a = c["agg"]
        fn = c["floor_name"]
        x = a["dist_ft_mid"].values.astype(float)
        y = a[Y_STAT].values.astype(float)
        x, y = _prepend_zero_point(x, y, method=ZERO_INSERT_METHOD, clamp_to_data=CLAMP_ZERO_TO_DATA_RANGE)
        avg_val = np.nanmean(y)
        stats.append({'curve': c, 'x': x, 'y': y, 'avg': avg_val, 'fn': fn})

    # Sort based on HIGHER_IS_BETTER
    if HIGHER_IS_BETTER:
        stats = sorted(stats, key=lambda item: item['avg'], reverse=True)
    else:
        stats = sorted(stats, key=lambda item: item['avg'])

    used_x, used_y = [], []
    unit_str = f" {UNIT_LABEL}" if UNIT_LABEL else ""

    for i, item in enumerate(stats):
        c = item['curve']
        x = item['x']
        y = item['y']
        avg_val = item['avg']
        fn = item['fn']
        a = c["agg"]

        used_x.append(x)
        used_y.append(y)

        color = COLOR_BY_FLOOR.get(fn, None)
        ls = STYLE_BY_FLOOR.get(fn, "-") if "STYLE_BY_FLOOR" in globals() else "-"

        # Updated Label: Show Avg instead of Drop
        line, = ax.plot(
            x, y,
            color=color, linestyle=ls, linewidth=LINEWIDTH, alpha=ALPHA,
            label=f"{fn} | avg: {avg_val:.1f}{unit_str}", zorder=2 + i
        )

        if _HAS_PE and OUTLINE:
            line.set_path_effects([pe.Stroke(linewidth=OUTLINE_WIDTH, foreground=OUTLINE_COLOR), pe.Normal()])

        if FILL_SPREAD and ("p10" in a.columns) and ("p90" in a.columns):
            y10 = a["p10"].values.astype(float)
            y90 = a["p90"].values.astype(float)
            _, y10 = _prepend_zero_point(a["dist_ft_mid"].values.astype(float), y10, method=ZERO_INSERT_METHOD, clamp_to_data=True)
            _, y90 = _prepend_zero_point(a["dist_ft_mid"].values.astype(float), y90, method=ZERO_INSERT_METHOD, clamp_to_data=True)
            ax.fill_between(x, y10, y90, alpha=0.10, color=color, zorder=1)

    short_router = _router_name_only(router_key, router_display)
    ylabel = f"{PARAM_PRETTY} ({UNIT_LABEL})" if UNIT_LABEL else f"{PARAM_PRETTY}"

    ax.set_title(f"{PARAM_PRETTY} (Actual) — {band} — Router: {short_router} (floors)")
    ax.set_xlabel("Distance from DUT (ft)")
    ax.set_ylabel(ylabel)
    ax.grid(True, alpha=0.22)

    if used_x:
        ax.legend(loc="best", fontsize=LEGEND_FONTSIZE, ncols=_legend_cols(len(used_x)), frameon=True, framealpha=0.85)
        all_x, all_y = np.concatenate(used_x), np.concatenate(used_y)
        xmin, xmax = pad_limits(float(np.nanmin(all_x)), float(np.nanmax(all_x)), 0.04)
        ymin, ymax = pad_limits(float(np.nanmin(all_y)), float(np.nanmax(all_y)), 0.08)
        ax.set_xlim(left=0.0, right=xmax)
        ax.set_ylim(bottom=ymin, top=ymax)

    fig.tight_layout()
    meta_path = out_png.replace(".png", ".meta.json")
    save_plot_with_meta(fig, ax, out_png, meta_path)
    plt.show() # Inline plotting left active
    print("[OK] Saved:", out_png)
    return (out_png, meta_path)

# ------------------ Run ------------------
saved_act_router_floors = []

for band in BANDS:
    band_curves = [c for c in CURVES if c["band"] == band]
    if not band_curves: continue

    for rk in sorted(set([c["router_key"] for c in band_curves])):
        rc = [c for c in band_curves if c["router_key"] == rk]
        if not rc: continue

        router_display = rc[0].get("router_display", rk)
        out_png = os.path.join(PLOTS_DIR_ACT, "COMPARE_FLOORS_BY_ROUTER", f"{PARAM_KEY}__act__{band}__router_{rk}.png")
        os.makedirs(os.path.dirname(out_png), exist_ok=True)

        saved_act_router_floors.append(plot_router_floors_actual(rc, band, rk, router_display, out_png))

print("[INFO] Total saved (actual, floors-by-router):", len(saved_act_router_floors))

"""## Export (zip outputs)

### download outputs
"""

# =========================
# FINAL) Zip ALL outputs (overwrite previous zip each run)
# - Creates ONE zip in /content
# - Replaces existing zip with same name
# =========================
import os, zipfile
from pathlib import Path

# What to zip (your full output folder)
SRC_DIR = OUT_BASE  # e.g., "/content/rvr_data_rate" or "/content/rvr_signal_strength"

# Fixed zip name (same every run -> overwrites)
ZIP_NAME = "rvr_full_output.zip"
ZIP_PATH = 'runs/router/rvr_full_output_data_rate.zip'

def zip_folder_overwrite(src_dir: str, zip_path: str):
    src_dir = os.path.abspath(src_dir)
    if not os.path.isdir(src_dir):
        raise FileNotFoundError(f"SRC_DIR not found: {src_dir}")

    # Remove old zip if exists
    if os.path.exists(zip_path):
        os.remove(zip_path)
        print("[OK] Removed previous zip:", zip_path)

    files_added = 0
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for p in Path(src_dir).rglob("*"):
            if p.is_file():
                arcname = os.path.relpath(str(p), start=os.path.dirname(src_dir))
                zf.write(str(p), arcname=arcname)
                files_added += 1

    size_mb = os.path.getsize(zip_path) / (1024 * 1024)
    print(f"[OK] Created zip: {zip_path}")
    print(f"[INFO] Files added: {files_added}")
    print(f"[INFO] Zip size: {size_mb:.2f} MB")
    return zip_path

zip_path = zip_folder_overwrite(SRC_DIR, ZIP_PATH)

# Optional: download to local machine (uncomment in Colab)
if IN_COLAB:
    from google.colab import files
    files.download(zip_path)
else:
    print("[OK] Zip ready:", zip_path)
